Jakopter: src/video_display.c File Reference
video_display.c File Reference
#include <stdint.h>
#include <SDL2/SDL.h>
#include <pthread.h>
#include "SDL_ttf.h"
#include "SDL_image.h"
#include "video_display.h"
Data Structures
struct graphics_t
struct graphics_list
Macros
#define TEXT_BUF_SIZE 100
#define PI 3.14159265
Functions
static struct graphics_list * video_graphic_create ()
static void video_graphic_destroy (struct graphics_list *del)
static int load_element ()
static int unload_element ()
static int video_init_text (char *font_path)
static void video_clean_text ()
static SDL_Texture * video_make_text (char *text, int *res_w, int *res_h)
static SDL_Texture * video_import_png (char *path, int *res_w, int *res_h)
static void update_infos ()
static void take_screenshot (uint8_t *frame, int size)
static void draw_attitude_indic ()
static void draw_compass ()
static void rotate_point (SDL_Point *point, const SDL_Point *center, float angle)
static int video_display_init_size (int width, int height)
static int video_display_set_size (int w, int h)
int video_display_init ()
void video_display_destroy ()
struct graphics_list * video_graphic_create (int type)
int video_display_process (uint8_t *frame, int width, int height, int size)
static int graphic_append (struct graphics_list *item)
int display_draw_icon (const char *path, int x, int y, int width, int height)
int display_draw_text (const char *string, int x, int y)
void display_graphic_remove (int id)
void display_graphic_resize (int id, int width, int height)
void display_graphic_move (int id, int x, int y)
Variables
graphics_t graphs [VIDEO_NB_NAV_INFOS]
static struct graphics_list * icon_registry = NULL
static struct graphics_list * load_icon = NULL
static pthread_mutex_t mutex_graphics_list = PTHREAD_MUTEX_INITIALIZER
static jakopter_com_channel_t * com_in
static SDL_Window * win = NULL
static SDL_Renderer * renderer = NULL
static SDL_Texture * frameTex = NULL
static int current_width = 0
static int current_height = 0
static float pitch = 0
static float roll = 0
static float yaw = 0
static float speed = 0
static int initialized = 0
static double prev_update = 0
static TTF_Font * font
static SDL_Color text_color = {0, 200, 0}
static int want_screenshot = 0
static int screenshot_nb = 0
static char * screenshot_baseName = "screen_"
int horiz_posx
int horiz_posy
int horiz_size
float horiz_pitchScale = 1
int compass_x = 0
int compass_y = 0
int compass_w = 200
int compass_h = 50
int compass_nbBars = 8
int compass_scale = 1
Macro Definition Documentation
#define PI 3.14159265
Definition at line 11 of file video_display.c.
Referenced by rotate_point().
#define TEXT_BUF_SIZE 100
Definition at line 10 of file video_display.c.
Referenced by update_infos().
Function Documentation
int display_draw_icon (const char * path, int x, int y, int width, int height)
Draw an icon on the video display. width and height are facultative, set it to 0.
Parameters
path the relative path to the icon
x in pixels from left
y in pixels from top
width in pixels, optional
height in pixels, optional
Returns
the icon id
Definition at line 639 of file video_display.c.
References current_height, current_width, graphics_list::graphic, graphic_append(), graphics_list::id, mutex_graphics_list, graphics_t::pos, graphics_list::string, graphics_t::tex, video_graphic_create(), and VIDEO_ICON.
int display_draw_text (const char * string, int x, int y)
Draw a string on the video display.
Parameters
string the text to print
x in pixels from left
y in pixels from top
Returns
the icon id
Definition at line 677 of file video_display.c.
References graphics_list::graphic, graphic_append(), graphics_list::id, mutex_graphics_list, graphics_t::pos, graphics_list::string, graphics_t::tex, video_graphic_create(), and VIDEO_TEXT.
void display_graphic_move (int id, int x, int y)
Move a graphic element on the display window.
Parameters
id the id returned by display_draw_...
x in pixels from left
y in pixels from top
Definition at line 753 of file video_display.c.
References current_height, current_width, graphics_list::graphic, icon_registry, graphics_list::id, initialized, mutex_graphics_list, graphics_list::next, and graphics_t::pos.
void display_graphic_remove (int id)
Free the memory associated with the graphic element.
Definition at line 704 of file video_display.c.
References DISPLAY_CYCLES, icon_registry, graphics_list::id, mutex_graphics_list, graphics_list::next, and graphics_list::time_to_live.
Referenced by load_element().
void display_graphic_resize (int id, int width, int height)
Resize a graphic element on the display window.
Parameters
id the id returned by display_draw_...
width in pixels
height in pixels
Definition at line 730 of file video_display.c.
References current_height, current_width, graphics_list::graphic, icon_registry, graphics_list::id, mutex_graphics_list, graphics_list::next, and graphics_t::pos.
void draw_attitude_indic () static
simple attitude indicator with the horizon represented by a straight line and the drone by a line with a center point.
Definition at line 791 of file video_display.c.
References horiz_pitchScale, horiz_posx, horiz_posy, horiz_size, pitch, renderer, roll, and rotate_point().
Referenced by video_display_process().
void draw_compass () static
draw every vertical bar of the compass. Their position reflects the drone's yaw value.
Definition at line 819 of file video_display.c.
References compass_h, compass_nbBars, compass_scale, compass_w, compass_x, compass_y, renderer, and yaw.
Referenced by video_display_process().
static int graphic_append (struct graphics_list * item) static
Append a graphic element to the list of overlayed elements.
Parameters
item a new element
Returns
the id of the element
Definition at line 618 of file video_display.c.
References icon_registry, graphics_list::id, mutex_graphics_list, and graphics_list::next.
Referenced by display_draw_icon(), and display_draw_text().
int load_element () static
Create the SDL object associated with a graphical element. With SDL, we can't create or destroy texture from a different thread than the rendering one.
Returns
0 if it's ok, -1 otherwise
Definition at line 459 of file video_display.c.
References current_height, current_width, display_graphic_remove(), graphics_list::graphic, icon_registry, graphics_list::id, mutex_graphics_list, graphics_list::next, graphics_t::pos, graphics_list::string, graphics_t::tex, graphics_list::type, VIDEO_ICON, video_import_png(), video_make_text(), and VIDEO_TEXT.
Referenced by video_display_process().
void rotate_point (SDL_Point * point, const SDL_Point * center, float angle) static
used by draw_attitude_indic
Definition at line 834 of file video_display.c.
References PI.
Referenced by draw_attitude_indic().
void take_screenshot (uint8_t * frame, int size) static
Save the current frame in a file called screen_d.yuv with d a number incremented each screenshot.
Parameters
frame current frame
size in bytes
Definition at line 854 of file video_display.c.
References screenshot_baseName, and screenshot_nb.
Referenced by video_display_process().
static int unload_element () static
Remove the SDL object associated with a graphical element, caring it has been printed one time. With SDL, we can't create or destroy texture from a different thread than the rendering one.
Returns
0 if it's ok, -1 otherwise
Definition at line 543 of file video_display.c.
References icon_registry, mutex_graphics_list, graphics_list::next, graphics_list::time_to_live, and video_graphic_destroy().
Referenced by video_display_process().
void update_infos () static
Used to show some basic navdata from a com_channel.
Definition at line 576 of file video_display.c.
References font, jakopter_com_read_float(), jakopter_com_read_int(), pitch, graphics_t::pos, roll, speed, graphics_t::tex, TEXT_BUF_SIZE, video_make_text(), want_screenshot, and yaw.
Referenced by video_display_process().
static void video_clean_text () static
Clean SDL_TTF stuff.
Definition at line 207 of file video_display.c.
References font.
Referenced by video_display_destroy().
void video_display_destroy ()
Free the memory associated with the module. Clean the display context : close the window and clean SDL structures.
Definition at line 252 of file video_display.c.
References CHANNEL_DISPLAY, frameTex, icon_registry, initialized, jakopter_com_remove_channel(), mutex_graphics_list, graphics_list::next, renderer, video_clean_text(), video_graphic_destroy(), VIDEO_NB_NAV_INFOS, and win.
Referenced by video_display_process().
int video_display_init ()
Create the com_channel needed to communicate with the display module.
Definition at line 240 of file video_display.c.
References CHANNEL_DISPLAY, DISPLAY_COM_IN_SIZE, jakopter_com_add_channel(), and prev_update.
static int video_display_init_size (int width, int height) static
Initialize SDL, create the window and the renderer to get ready to draw frames.
Parameters
width in pixels
height in pixels
Returns
0 on success, -1 on error.
Definition at line 151 of file video_display.c.
References FONT_PATH, pitch, renderer, roll, video_init_text(), VIDEO_NB_NAV_INFOS, and win.
Referenced by video_display_process().
int video_display_process (uint8_t * frame, int width, int height, int size)
"Got frame" callback. Fills the texture with the given frame, and displays it on the window.
Definition at line 323 of file video_display.c.
References current_height, current_width, draw_attitude_indic(), draw_compass(), frameTex, graphics_list::graphic, icon_registry, initialized, jakopter_com_get_timestamp(), jakopter_com_write_int(), load_element(), mutex_graphics_list, graphics_list::next, graphics_t::pos, prev_update, renderer, take_screenshot(), graphics_t::tex, unload_element(), update_infos(), video_display_destroy(), video_display_init_size(), video_display_set_size(), VIDEO_NB_NAV_INFOS, and want_screenshot.
static int video_display_set_size (int w, int h) static
Set the size of the window and of the texture containing the video. The parameters become the current size.
Parameters
w width in pixels
h height in pixels
Returns
0 it's ok, -1 SDL has been lost in another dimension
Definition at line 220 of file video_display.c.
References compass_h, compass_x, compass_y, current_height, current_width, frameTex, horiz_pitchScale, horiz_posx, horiz_posy, horiz_size, renderer, and win.
Referenced by video_display_process().
static struct graphics_list* video_graphic_create () static
Referenced by display_draw_icon(), and display_draw_text().
struct graphics_list* video_graphic_create (int type)
initialize a graphics_list element
Parameters
type icon or text
Returns
a pointer to the element
Definition at line 288 of file video_display.c.
References graphics_list::graphic, graphics_list::id, graphics_list::next, graphics_list::string, graphics_list::time_to_live, and graphics_list::type.
void video_graphic_destroy (struct graphics_list * del) static
delete a graphics_list element
Parameters
del an element you doesn't want anymore
Definition at line 303 of file video_display.c.
References graphics_list::graphic, graphics_list::string, and graphics_t::tex.
Referenced by unload_element(), and video_display_destroy().
SDL_Texture * video_import_png (char * path, int * res_w, int * res_h) static
Create an SDL_Texture from a PNG file.
Parameters
path relative path
res_w width of the PNG in pixels
res_h height of the PNG in pixels
Definition at line 421 of file video_display.c.
References renderer.
Referenced by load_element().
static int video_init_text (char * font_path) static
Init SDL stuff.
Definition at line 192 of file video_display.c.
References font.
Referenced by video_display_init_size().
SDL_Texture * video_make_text (char * text, int * res_w, int * res_h) static
Create an SDL_Texture from a string.
Parameters
text a raptor ate this description
res_w width of the PNG in pixels
res_h height of the PNG in pixels
Definition at line 404 of file video_display.c.
References font, renderer, and text_color.
Referenced by load_element(), and update_infos().
Variable Documentation
jakopter_com_channel_t* com_in static
Definition at line 59 of file video_display.c.
int compass_h = 50
Definition at line 131 of file video_display.c.
Referenced by draw_compass(), and video_display_set_size().
int compass_nbBars = 8
Definition at line 133 of file video_display.c.
Referenced by draw_compass().
int compass_scale = 1
Definition at line 135 of file video_display.c.
Referenced by draw_compass().
int compass_w = 200
Definition at line 131 of file video_display.c.
Referenced by draw_compass().
int compass_x = 0
Definition at line 129 of file video_display.c.
Referenced by draw_compass(), and video_display_set_size().
int compass_y = 0
Definition at line 129 of file video_display.c.
Referenced by draw_compass(), and video_display_set_size().
int current_height = 0 static
Definition at line 76 of file video_display.c.
Referenced by display_draw_icon(), display_graphic_move(), display_graphic_resize(), load_element(), video_display_process(), and video_display_set_size().
int current_width = 0 static
Definition at line 76 of file video_display.c.
Referenced by display_draw_icon(), display_graphic_move(), display_graphic_resize(), load_element(), video_display_process(), and video_display_set_size().
TTF_Font* font static
Definition at line 92 of file video_display.c.
Referenced by update_infos(), video_clean_text(), video_init_text(), and video_make_text().
SDL_Texture* frameTex = NULL static
Definition at line 71 of file video_display.c.
Referenced by video_display_destroy(), video_display_process(), and video_display_set_size().
graphics_t graphs[VIDEO_NB_NAV_INFOS]
List of all overlayed graphical elements. For now, navdata text only.
Definition at line 24 of file video_display.c.
float horiz_pitchScale = 1
Definition at line 123 of file video_display.c.
Referenced by draw_attitude_indic(), and video_display_set_size().
int horiz_posx
Definition at line 119 of file video_display.c.
Referenced by draw_attitude_indic(), and video_display_set_size().
int horiz_posy
Definition at line 119 of file video_display.c.
Referenced by draw_attitude_indic(), and video_display_set_size().
int horiz_size
Definition at line 121 of file video_display.c.
Referenced by draw_attitude_indic(), and video_display_set_size().
struct graphics_list* icon_registry = NULL static
Pointer to the first overlayed element
Definition at line 43 of file video_display.c.
Referenced by display_graphic_move(), display_graphic_remove(), display_graphic_resize(), graphic_append(), load_element(), unload_element(), video_display_destroy(), and video_display_process().
int initialized = 0 static
Definition at line 87 of file video_display.c.
Referenced by display_graphic_move(), video_display_destroy(), and video_display_process().
struct graphics_list* load_icon = NULL static
Pointer to the next overlayed element to load
Definition at line 45 of file video_display.c.
pthread_mutex_t mutex_graphics_list = PTHREAD_MUTEX_INITIALIZER static
Race condition between rendering and list append
Definition at line 52 of file video_display.c.
Referenced by display_draw_icon(), display_draw_text(), display_graphic_move(), display_graphic_remove(), display_graphic_resize(), graphic_append(), load_element(), unload_element(), video_display_destroy(), and video_display_process().
float pitch = 0 static
Definition at line 81 of file video_display.c.
Referenced by draw_attitude_indic(), update_infos(), and video_display_init_size().
double prev_update = 0 static
Definition at line 89 of file video_display.c.
Referenced by video_display_init(), and video_display_process().
SDL_Renderer* renderer = NULL static
Definition at line 67 of file video_display.c.
Referenced by draw_attitude_indic(), draw_compass(), video_display_destroy(), video_display_init_size(), video_display_process(), video_display_set_size(), video_import_png(), and video_make_text().
float roll = 0 static
Definition at line 81 of file video_display.c.
Referenced by draw_attitude_indic(), update_infos(), and video_display_init_size().
char* screenshot_baseName = "screen_" static
Definition at line 111 of file video_display.c.
Referenced by take_screenshot().
int screenshot_nb = 0 static
Definition at line 109 of file video_display.c.
Referenced by take_screenshot().
float speed = 0 static
Definition at line 82 of file video_display.c.
Referenced by jakopter_backward_lua(), jakopter_down_lua(), jakopter_forward_lua(), jakopter_slide_left_lua(), jakopter_slide_right_lua(), jakopter_up_lua(), and update_infos().
SDL_Color text_color = {0, 200, 0} static
Definition at line 93 of file video_display.c.
Referenced by video_make_text().
int want_screenshot = 0 static
Definition at line 107 of file video_display.c.
Referenced by update_infos(), and video_display_process().
SDL_Window* win = NULL static
Definition at line 63 of file video_display.c.
Referenced by video_display_destroy(), video_display_init_size(), and video_display_set_size().
float yaw = 0 static
Definition at line 81 of file video_display.c.
Referenced by draw_compass(), and update_infos().