# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/pi/Jakopter

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/pi/Jakopter

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pi/Jakopter/CMakeFiles /home/pi/Jakopter/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pi/Jakopter/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named jakopter

# Build rule for target.
jakopter: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 jakopter
.PHONY : jakopter

# fast build rule for target.
jakopter/fast:
	$(MAKE) -f CMakeFiles/jakopter.dir/build.make CMakeFiles/jakopter.dir/build
.PHONY : jakopter/fast

src/drone.o: src/drone.c.o
.PHONY : src/drone.o

# target to build an object file
src/drone.c.o:
	$(MAKE) -f CMakeFiles/jakopter.dir/build.make CMakeFiles/jakopter.dir/src/drone.c.o
.PHONY : src/drone.c.o

src/drone.i: src/drone.c.i
.PHONY : src/drone.i

# target to preprocess a source file
src/drone.c.i:
	$(MAKE) -f CMakeFiles/jakopter.dir/build.make CMakeFiles/jakopter.dir/src/drone.c.i
.PHONY : src/drone.c.i

src/drone.s: src/drone.c.s
.PHONY : src/drone.s

# target to generate assembly for a file
src/drone.c.s:
	$(MAKE) -f CMakeFiles/jakopter.dir/build.make CMakeFiles/jakopter.dir/src/drone.c.s
.PHONY : src/drone.c.s

src/lua_bindings.o: src/lua_bindings.c.o
.PHONY : src/lua_bindings.o

# target to build an object file
src/lua_bindings.c.o:
	$(MAKE) -f CMakeFiles/jakopter.dir/build.make CMakeFiles/jakopter.dir/src/lua_bindings.c.o
.PHONY : src/lua_bindings.c.o

src/lua_bindings.i: src/lua_bindings.c.i
.PHONY : src/lua_bindings.i

# target to preprocess a source file
src/lua_bindings.c.i:
	$(MAKE) -f CMakeFiles/jakopter.dir/build.make CMakeFiles/jakopter.dir/src/lua_bindings.c.i
.PHONY : src/lua_bindings.c.i

src/lua_bindings.s: src/lua_bindings.c.s
.PHONY : src/lua_bindings.s

# target to generate assembly for a file
src/lua_bindings.c.s:
	$(MAKE) -f CMakeFiles/jakopter.dir/build.make CMakeFiles/jakopter.dir/src/lua_bindings.c.s
.PHONY : src/lua_bindings.c.s

src/navdata.o: src/navdata.c.o
.PHONY : src/navdata.o

# target to build an object file
src/navdata.c.o:
	$(MAKE) -f CMakeFiles/jakopter.dir/build.make CMakeFiles/jakopter.dir/src/navdata.c.o
.PHONY : src/navdata.c.o

src/navdata.i: src/navdata.c.i
.PHONY : src/navdata.i

# target to preprocess a source file
src/navdata.c.i:
	$(MAKE) -f CMakeFiles/jakopter.dir/build.make CMakeFiles/jakopter.dir/src/navdata.c.i
.PHONY : src/navdata.c.i

src/navdata.s: src/navdata.c.s
.PHONY : src/navdata.s

# target to generate assembly for a file
src/navdata.c.s:
	$(MAKE) -f CMakeFiles/jakopter.dir/build.make CMakeFiles/jakopter.dir/src/navdata.c.s
.PHONY : src/navdata.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... jakopter"
	@echo "... rebuild_cache"
	@echo "... src/drone.o"
	@echo "... src/drone.i"
	@echo "... src/drone.s"
	@echo "... src/lua_bindings.o"
	@echo "... src/lua_bindings.i"
	@echo "... src/lua_bindings.s"
	@echo "... src/navdata.o"
	@echo "... src/navdata.i"
	@echo "... src/navdata.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

