Jakopter: include/network.h File Reference
network.h File Reference
#include "com_channel.h"
#include "com_master.h"
#include "utils.h"
Macros
#define CHANNEL_INPUT_SIZE 16384
#define CHANNEL_OUTPUT_SIZE 1024
#define ORDER_SIZE 256
#define DEFAULT_CLIENT_IN "http://127.0.0.1"
#define DEFAULT_CLIENT_OUT "http://127.0.0.1/index.php"
#define TIMEOUT_NETWORK 10000000
Functions
int jakopter_init_network (const char *server_in, const char *server_out)
int jakopter_stop_network ()
Macro Definition Documentation
#define CHANNEL_INPUT_SIZE 16384
Definition at line 7 of file network.h.
Referenced by jakopter_init_network().
#define CHANNEL_OUTPUT_SIZE 1024
Definition at line 8 of file network.h.
Referenced by jakopter_init_network(), and send_routine().
#define DEFAULT_CLIENT_IN "http://127.0.0.1"
Definition at line 12 of file network.h.
Referenced by jakopter_init_network().
#define DEFAULT_CLIENT_OUT "http://127.0.0.1/index.php"
Definition at line 13 of file network.h.
Referenced by jakopter_init_network().
#define ORDER_SIZE 256
Definition at line 10 of file network.h.
Referenced by send_routine().
#define TIMEOUT_NETWORK 10000000
Definition at line 16 of file network.h.
Referenced by receive_routine(), and send_routine().
Function Documentation
int jakopter_init_network (const char * server_in, const char * server_out)
Start the thread that listen on server_in and send data on server_out.
Parameters
server_in a HTTP address where Curl GET his data
server_out a HTTP address where Curl POST his data
Returns
0 OK, -1 otherwise
Definition at line 136 of file network.c.
References CHANNEL_INPUT_SIZE, CHANNEL_NETWORK_INPUT, CHANNEL_NETWORK_OUTPUT, CHANNEL_OUTPUT_SIZE, DEFAULT_CLIENT_IN, DEFAULT_CLIENT_OUT, jakopter_com_add_channel(), receive_routine(), receive_thread, recv_addr, recv_ready, send_addr, send_routine(), send_thread, and stopped_network.
Referenced by jakopter_init_network_lua().
int jakopter_stop_network ()
Stop curl.
Definition at line 184 of file network.c.
References CHANNEL_NETWORK_INPUT, CHANNEL_NETWORK_OUTPUT, jakopter_com_remove_channel(), receive_thread, recv_ready, send_thread, and stopped_network.
Referenced by jakopter_cleanup_lua(), and jakopter_stop_network_lua().