Jakopter: src/coords.c File Reference
coords.c File Reference
#include <stdlib.h>
#include <stdio.h>
#include <stdbool.h>
#include <unistd.h>
#include <fcntl.h>
#include <errno.h>
#include <pthread.h>
#include <arpa/inet.h>
#include <sys/types.h>
#include <sys/time.h>
#include <sys/un.h>
#include "coords.h"
Functions
static int read_coords (float num[COORDS_NREADS])
void * coords_routine (void *args)
int jakopter_init_coords ()
int jakopter_stop_coords ()
const char * jakopter_log_coords ()
Variables
static char log_coords [TSTAMP_LEN+COORDS_BUF_SIZE]
struct sockaddr_un addr_server_coords
int sock_coords
jakopter_com_channel_t * coords_channel
pthread_t coords_thread
static bool recv_ready = false
static bool stopped_coords = true
static pthread_mutex_t mutex_stopped_coords = PTHREAD_MUTEX_INITIALIZER
static pthread_mutex_t mutex_log = PTHREAD_MUTEX_INITIALIZER
Function Documentation
void* coords_routine (void * args)
Definition at line 77 of file coords.c.
References COORDS_INTERVAL, COORDS_NREADS, jakopter_com_write_float(), mutex_stopped_coords, read_coords(), recv_ready, and stopped_coords.
Referenced by jakopter_init_coords().
int jakopter_init_coords ()
Definition at line 98 of file coords.c.
References addr_server_coords, CHANNEL_COORDS, COORDS_FILENAME, COORDS_NREADS, coords_routine(), coords_thread, COORDS_TIMEOUT, jakopter_com_add_channel(), jakopter_com_write_float(), mutex_stopped_coords, recv_ready, sock_coords, and stopped_coords.
Referenced by jakopter_init_coords_lua().
const char* jakopter_log_coords ()
Definition at line 171 of file coords.c.
References COORDS_BUF_SIZE, log_coords, mutex_log, stopped_coords, and TSTAMP_LEN.
Referenced by jakopter_log_coords_lua().
int jakopter_stop_coords ()
Definition at line 147 of file coords.c.
References CHANNEL_COORDS, COORDS_FILENAME, coords_thread, jakopter_com_remove_channel(), mutex_stopped_coords, sock_coords, and stopped_coords.
Referenced by jakopter_cleanup_lua(), and jakopter_stop_coords_lua().
static int read_coords (float num[COORDS_NREADS]) static
Definition at line 29 of file coords.c.
References addr_server_coords, COORDS_BUF_SIZE, log_coords, mutex_log, sock_coords, and TSTAMP_LEN.
Referenced by coords_routine().
Variable Documentation
struct sockaddr_un addr_server_coords
Definition at line 17 of file coords.c.
Referenced by jakopter_init_coords(), and read_coords().
jakopter_com_channel_t* coords_channel
Definition at line 20 of file coords.c.
pthread_t coords_thread
Definition at line 21 of file coords.c.
Referenced by jakopter_init_coords(), and jakopter_stop_coords().
char log_coords[TSTAMP_LEN+COORDS_BUF_SIZE] static
Definition at line 16 of file coords.c.
Referenced by jakopter_log_coords(), and read_coords().
pthread_mutex_t mutex_log = PTHREAD_MUTEX_INITIALIZER static
Definition at line 27 of file coords.c.
Referenced by jakopter_log_coords(), and read_coords().
pthread_mutex_t mutex_stopped_coords = PTHREAD_MUTEX_INITIALIZER static
Definition at line 25 of file coords.c.
Referenced by coords_routine(), jakopter_init_coords(), and jakopter_stop_coords().
bool recv_ready = false static
Definition at line 23 of file coords.c.
Referenced by coords_routine(), and jakopter_init_coords().
int sock_coords
Definition at line 18 of file coords.c.
Referenced by jakopter_init_coords(), jakopter_stop_coords(), and read_coords().
bool stopped_coords = true static
Definition at line 24 of file coords.c.
Referenced by coords_routine(), jakopter_init_coords(), jakopter_log_coords(), and jakopter_stop_coords().