Jakopter: src/navdata.c File Reference
navdata.c File Reference
#include "common.h"
#include "navdata.h"
#include "drone.h"
Macros
#define LOG_LEN TSTAMP_LEN+DEMO_LEN+1
Functions
static void navdata_timestamp ()
static int recv_cmd ()
static int navdata_init ()
void * navdata_routine (void *args)
int navdata_connect (const char *drone_ip)
int navdata_disconnect ()
JAKO_EXPORT int jakopter_is_flying ()
JAKO_EXPORT int jakopter_battery ()
JAKO_EXPORT int jakopter_height ()
int navdata_no_sq ()
void debug_navdata_demo ()
JAKO_EXPORT const char * jakopter_log_navdata ()
Variables
static union navdata_t data
static char timestamp [TSTAMP_LEN]
jakopter_com_channel_t * nav_channel
pthread_t navdata_thread
static bool stopped_navdata = true
static pthread_mutex_t mutex_navdata = PTHREAD_MUTEX_INITIALIZER
static pthread_mutex_t mutex_stopped = PTHREAD_MUTEX_INITIALIZER
static pthread_mutex_t mutex_timestamp = PTHREAD_MUTEX_INITIALIZER
static struct sockaddr_in addr_drone_navdata addr_client_navdata
static int sock_navdata
Macro Definition Documentation
#define LOG_LEN TSTAMP_LEN+DEMO_LEN+1
Definition at line 5 of file navdata.c.
Referenced by jakopter_log_navdata().
Function Documentation
void debug_navdata_demo ()
Print the content of received navdata.
Definition at line 288 of file navdata.c.
References navdata_demo::ardrone_state, navdata_demo::ctrl_state, data, navdata_t::demo, navdata_demo::header, mutex_navdata, navdata_demo::phi, navdata_demo::psi, navdata_demo::sequence, navdata_demo::size, navdata_demo::tag, and navdata_demo::theta.
JAKO_EXPORT int jakopter_battery ()
Returns
the battery charge in percentage or -1 if navdata are not received
Definition at line 247 of file navdata.c.
References data, navdata_t::demo, mutex_navdata, navdata::options, navdata_t::raw, navdata::sequence, navdata_option::tag, TAG_DEMO, and navdata_demo::vbat_flying_percentage.
Referenced by jakopter_battery_lua().
JAKO_EXPORT int jakopter_height ()
Returns
the height in millimeters or -1 if navdata are not received
Definition at line 263 of file navdata.c.
References navdata_demo::altitude, data, navdata_t::demo, mutex_navdata, navdata::options, navdata_t::raw, navdata::sequence, navdata_option::tag, and TAG_DEMO.
Referenced by jakopter_height_lua(), jakopter_land(), and jakopter_takeoff().
JAKO_EXPORT int jakopter_is_flying ()
Returns
a boolean
Definition at line 238 of file navdata.c.
References navdata::ardrone_state, data, mutex_navdata, and navdata_t::raw.
Referenced by jakopter_calib(), jakopter_cleanup_lua(), jakopter_flat_trim(), jakopter_is_flying_lua(), jakopter_land(), and jakopter_takeoff().
JAKO_EXPORT const char* jakopter_log_navdata ()
Return all the data stored with a timestamp.
Returns
a string containing the data under this format: "sec.nsec:data1 data2 " or NULL if stopped
Definition at line 303 of file navdata.c.
References navdata_demo::altitude, navdata_demo::ardrone_state, navdata_demo::ctrl_state, data, navdata_t::demo, DEMO_LEN, LOG_LEN, mutex_navdata, mutex_timestamp, navdata_demo::phi, navdata_demo::psi, stopped_navdata, navdata_demo::theta, timestamp, TSTAMP_LEN, navdata_demo::vbat_flying_percentage, navdata_demo::vx, navdata_demo::vy, and navdata_demo::vz.
Referenced by jakopter_log_navdata_lua().
int navdata_connect (const char * drone_ip)
Start navdata thread.
Parameters
drone_ip used by simulator, if you are with a real drone, set it to NULL
Returns
0 if success, -1 if error
Definition at line 167 of file navdata.c.
References addr_client_navdata, CHANNEL_NAVDATA, data, jakopter_com_add_channel(), mutex_stopped, navdata_init(), navdata_routine(), navdata_thread, PORT_NAVDATA, sock_navdata, stopped_navdata, and WIFI_ARDRONE_IP.
Referenced by jakopter_connect().
int navdata_disconnect ()
Stop navdata thread.
Returns
the pthread_join value or -1 if communication already stopped.
Definition at line 214 of file navdata.c.
References CHANNEL_NAVDATA, jakopter_com_remove_channel(), mutex_stopped, navdata_thread, sock_navdata, and stopped_navdata.
Referenced by jakopter_disconnect().
static int navdata_init () static
Procedure to initialize the communication of navdata with the drone.
Returns
0 if success, -1 if an error occured
Definition at line 81 of file navdata.c.
References navdata::ardrone_state, config_ack(), data, init_navdata_bootstrap(), navdata_t::raw, recv_cmd(), and sock_navdata.
Referenced by navdata_connect().
int navdata_no_sq ()
Returns
the sequence number of navdata
Definition at line 279 of file navdata.c.
References data, mutex_navdata, navdata_t::raw, and navdata::sequence.
Referenced by jakopter_land(), and jakopter_takeoff().
void* navdata_routine (void * args)
navdata_thread routine which keep the connection alive.
Definition at line 143 of file navdata.c.
References mutex_stopped, NAVDATA_INTERVAL, recv_cmd(), sock_navdata, and stopped_navdata.
Referenced by navdata_connect().
static void navdata_timestamp () static
Definition at line 68 of file navdata.c.
References mutex_timestamp, timestamp, and TSTAMP_LEN.
Referenced by recv_cmd().
static int recv_cmd () static
Receive the navdata from the drone and write it in NAVDATA_CHANNEL.
Returns
the result of recvfrom
Definition at line 34 of file navdata.c.
References navdata_demo::altitude, data, navdata_t::demo, jakopter_com_write_float(), jakopter_com_write_int(), mutex_navdata, navdata_timestamp(), navdata_demo::phi, navdata_demo::psi, sock_navdata, navdata_demo::tag, TAG_DEMO, navdata_demo::theta, navdata_demo::vbat_flying_percentage, navdata_demo::vx, navdata_demo::vy, and navdata_demo::vz.
Referenced by navdata_init(), and navdata_routine().
Variable Documentation
struct sockaddr_in addr_drone_navdata addr_client_navdata static
Definition at line 27 of file navdata.c.
Referenced by navdata_connect().
union navdata_t data static
Definition at line 8 of file navdata.c.
Referenced by debug_navdata_demo(), jakopter_battery(), jakopter_height(), jakopter_is_flying(), jakopter_log_navdata(), navdata_connect(), navdata_init(), navdata_no_sq(), and recv_cmd().
pthread_mutex_t mutex_navdata = PTHREAD_MUTEX_INITIALIZER static
Definition at line 20 of file navdata.c.
Referenced by debug_navdata_demo(), jakopter_battery(), jakopter_height(), jakopter_is_flying(), jakopter_log_navdata(), navdata_no_sq(), and recv_cmd().
pthread_mutex_t mutex_stopped = PTHREAD_MUTEX_INITIALIZER static
Definition at line 22 of file navdata.c.
Referenced by navdata_connect(), navdata_disconnect(), and navdata_routine().
pthread_mutex_t mutex_timestamp = PTHREAD_MUTEX_INITIALIZER static
Definition at line 24 of file navdata.c.
Referenced by jakopter_log_navdata(), and navdata_timestamp().
jakopter_com_channel_t* nav_channel
Definition at line 13 of file navdata.c.
pthread_t navdata_thread
Definition at line 15 of file navdata.c.
Referenced by navdata_connect(), and navdata_disconnect().
int sock_navdata static
Definition at line 28 of file navdata.c.
Referenced by navdata_connect(), navdata_disconnect(), navdata_init(), navdata_routine(), and recv_cmd().
bool stopped_navdata = true static
Definition at line 18 of file navdata.c.
Referenced by jakopter_log_navdata(), navdata_connect(), navdata_disconnect(), and navdata_routine().
char timestamp[TSTAMP_LEN] static
Definition at line 10 of file navdata.c.
Referenced by jakopter_log_navdata(), and navdata_timestamp().