Jakopter: include/drone.h File Reference
drone.h File Reference
#include "common.h"
#include "navdata.h"
#include "com_channel.h"
#include "com_master.h"
Macros
#define PACKET_SIZE 256
#define PORT_CMD 5556
#define TIMEOUT_CMD 30000000
#define NAVDATA_ATTEMPT 10
#define HEIGHT_THRESHOLD 500
#define HEAD_LEN 10
#define ARG_LEN 30
#define ARGS_MAX 7
#define HEAD_REF "REF"
#define HEAD_PCMD "PCMD"
#define HEAD_CONFIG "CONFIG"
#define HEAD_CTRL "CTRL"
#define HEAD_COM_WATCHDOG "COMWDG"
#define HEAD_FTRIM "FTRIM"
#define HEAD_CALIB "CALIB"
Enumerations
enum video_channels {
VID_HORIZONTAL, VID_VERTICAL, VID_HORIZON_VERTICAL, VID_VERTICAL_HORIZON,
VID_SWITCH, VID_CHANNELS
}
Functions
int jakopter_connect (const char *drone_ip)
int jakopter_takeoff ()
int jakopter_land ()
int jakopter_emergency ()
int jakopter_reinit ()
int jakopter_disconnect ()
int jakopter_rotate_left (float speed)
int jakopter_rotate_right (float speed)
int jakopter_slide_left (float speed)
int jakopter_slide_right (float speed)
int jakopter_forward (float speed)
int jakopter_backward (float speed)
int jakopter_up (float speed)
int jakopter_down (float speed)
int jakopter_stay ()
int jakopter_move (float l_to_r, float b_to_f, float vertical_speed, float angular_speed)
int jakopter_switch_camera (unsigned int id)
const char * jakopter_log_command ()
int jakopter_flat_trim ()
int jakopter_calib ()
int init_navdata_bootstrap ()
int config_ack ()
Macro Definition Documentation
#define ARG_LEN 30
Definition at line 18 of file drone.h.
Referenced by send_cmd(), and set_cmd().
#define ARGS_MAX 7
Definition at line 19 of file drone.h.
Referenced by send_cmd(), and set_cmd().
#define HEAD_CALIB "CALIB"
Definition at line 28 of file drone.h.
Referenced by jakopter_calib().
#define HEAD_COM_WATCHDOG "COMWDG"
Definition at line 26 of file drone.h.
Referenced by jakopter_reinit().
#define HEAD_CONFIG "CONFIG"
Definition at line 24 of file drone.h.
Referenced by init_navdata_bootstrap(), and jakopter_switch_camera().
#define HEAD_CTRL "CTRL"
Definition at line 25 of file drone.h.
Referenced by config_ack().
#define HEAD_FTRIM "FTRIM"
Definition at line 27 of file drone.h.
Referenced by jakopter_flat_trim().
#define HEAD_LEN 10
Definition at line 17 of file drone.h.
Referenced by send_cmd().
#define HEAD_PCMD "PCMD"
Definition at line 23 of file drone.h.
Referenced by jakopter_move(), and jakopter_stay().
#define HEAD_REF "REF"
Definition at line 22 of file drone.h.
Referenced by jakopter_emergency(), jakopter_land(), and jakopter_takeoff().
#define HEIGHT_THRESHOLD 500
Definition at line 15 of file drone.h.
Referenced by jakopter_land(), and jakopter_takeoff().
#define NAVDATA_ATTEMPT 10
Definition at line 14 of file drone.h.
Referenced by jakopter_land(), and jakopter_takeoff().
#define PACKET_SIZE 256
Definition at line 9 of file drone.h.
Referenced by jakopter_connect(), and send_cmd().
#define PORT_CMD 5556
Definition at line 10 of file drone.h.
Referenced by jakopter_connect().
#define TIMEOUT_CMD 30000000
Definition at line 13 of file drone.h.
Referenced by cmd_routine().
Enumeration Type Documentation
enum video_channels
Enumerator
VID_HORIZONTAL
VID_VERTICAL
VID_HORIZON_VERTICAL
VID_VERTICAL_HORIZON
VID_SWITCH
VID_CHANNELS
Definition at line 30 of file drone.h.
Function Documentation
int config_ack ()
Command used by navdata to acknowledge navdata settings.
Returns
send return code or -1 if command couldn't be set.
Definition at line 137 of file drone.c.
References cmd_wait, HEAD_CTRL, send_cmd(), and set_cmd().
Referenced by navdata_init().
int init_navdata_bootstrap ()
Command used by navdata to define the type of navdata to "demo".
Returns
send return code or -1 if command couldn't be set.
Definition at line 120 of file drone.c.
References cmd_wait, HEAD_CONFIG, send_cmd(), and set_cmd().
Referenced by navdata_init().
int jakopter_backward (float speed)
Command to make the drone go backward with a defined speed.
Parameters
speed the speed in percentage between 0 and 1
Returns
0 if success, -1 if command couldn't be set.
Definition at line 490 of file drone.c.
References jakopter_move(), and jakopter_stay().
Referenced by jakopter_backward_lua().
int jakopter_calib ()
Calibration of the drone for smartphone accelerometer.
Returns
0 if success, -1 if the drone isn't flying or the command couldn't be set.
Definition at line 286 of file drone.c.
References cmd_wait, HEAD_CALIB, jakopter_is_flying(), and set_cmd().
Referenced by jakopter_calib_lua().
int jakopter_connect (const char * drone_ip)
Creates a socket and starts the command thread. Needs the computer to be connected to the drone wifi network.
Parameters
drone_ip used by simulator, if you are with a real drone, set it to NULL. 255.255.255.255 can't be used (see man inet_addr)
Returns
0 if success, -1 if error
Definition at line 181 of file drone.c.
References addr_client, cmd_no_sq, cmd_routine(), cmd_thread, command_logged, command_type, INT_LEN, mutex_cmd, mutex_stopped, navdata_connect(), PACKET_SIZE, PORT_CMD, sock_cmd, stopped, user_input_connect(), and WIFI_ARDRONE_IP.
Referenced by jakopter_connect_lua().
int jakopter_disconnect ()
Stop main thread (End of drone connection)
Returns
pthread_join value or -1 if the communication is already stopped
Definition at line 252 of file drone.c.
References cmd_thread, mutex_stopped, navdata_disconnect(), sock_cmd, stopped, and user_input_disconnect().
Referenced by jakopter_cleanup_lua(), and jakopter_disconnect_lua().
int jakopter_down (float speed)
Command to make the drone go down with a defined speed.
Parameters
speed the speed in percentage between 0 and 1
Returns
0 if success, -1 if command couldn't be set.
Definition at line 510 of file drone.c.
References jakopter_move(), and jakopter_stay().
Referenced by jakopter_down_lua().
int jakopter_emergency ()
Command to stop drone rotors.
Returns
0 if success, -1 if command couldn't be set.
Definition at line 415 of file drone.c.
References cmd_wait, emergency_arg, HEAD_REF, and set_cmd().
Referenced by jakopter_emergency_lua(), and jakopter_land().
int jakopter_flat_trim ()
Set the frame of reference of the drone before taking off.
Returns
0 if success, -1 if the drone is flying or the command couldn't be set.
Definition at line 269 of file drone.c.
References cmd_wait, HEAD_FTRIM, jakopter_is_flying(), and set_cmd().
Referenced by jakopter_ftrim_lua(), and jakopter_takeoff().
int jakopter_forward (float speed)
Command to make the drone go forward with a defined speed.
Parameters
speed the speed in percentage between 0 and 1
Returns
0 if success, -1 if command couldn't be set.
Definition at line 480 of file drone.c.
References jakopter_move(), and jakopter_stay().
Referenced by jakopter_forward_lua().
int jakopter_land ()
Command to land the drone. If no recent navdata are received, it sends the emergency command.
Returns
0 if success, -1 if error.
Definition at line 381 of file drone.c.
References cmd_wait, HEAD_REF, HEIGHT_THRESHOLD, jakopter_emergency(), jakopter_height(), jakopter_is_flying(), land_arg, NAVDATA_ATTEMPT, navdata_no_sq(), and set_cmd().
Referenced by jakopter_cleanup_lua(), and jakopter_land_lua().
const char* jakopter_log_command ()
Return a timestamp and the last command sent separated with a colon.
Returns
the last logged_command if connected, NULL otherwise.
Definition at line 553 of file drone.c.
References command_logged, LOG_LEN, mutex_cmd, and stopped.
Referenced by jakopter_log_command_lua().
int jakopter_move (float l_to_r, float b_to_f, float vertical_speed, float angular_speed)
define the movement of the drone (-1.0 to 1.0 values).
Parameters
l_to_r the speed from left to right
b_to_f the speed from backward to forward
vertical_speed the speed from down to up
angular_speed the angular speed to rotate the drone
Returns
0 if success, -1 if command couldn't be set.
Definition at line 520 of file drone.c.
References cmd_wait, HEAD_PCMD, INT_LEN, and set_cmd().
Referenced by jakopter_backward(), jakopter_down(), jakopter_forward(), jakopter_move_lua(), jakopter_rotate_left(), jakopter_rotate_right(), jakopter_slide_left(), jakopter_slide_right(), and jakopter_up().
int jakopter_reinit ()
Command to reset the communication watchdog.
Returns
0 if success, -1 if command couldn't be set.
Definition at line 331 of file drone.c.
References cmd_wait, HEAD_COM_WATCHDOG, and set_cmd().
Referenced by jakopter_reinit_lua().
int jakopter_rotate_left (float speed)
Command to make the drone rotate to the left with an angular speed.
Parameters
speed the angular speed in percentage between 0 and 1
Returns
0 if success, -1 if command couldn't be set.
Definition at line 440 of file drone.c.
References jakopter_move(), and jakopter_stay().
Referenced by jakopter_rotate_left_lua().
int jakopter_rotate_right (float speed)
Command to make the drone rotate to the right with an angular speed.
Parameters
speed the angular speed in percentage between 0 and 1
Returns
0 if success, -1 if command couldn't be set.
Definition at line 450 of file drone.c.
References jakopter_move(), and jakopter_stay().
Referenced by jakopter_rotate_right_lua().
int jakopter_slide_left (float speed)
Command to make the drone slide to the left with a defined speed.
Parameters
speed the speed in percentage between 0 and 1
Returns
0 if success, -1 if command couldn't be set.
Definition at line 460 of file drone.c.
References jakopter_move(), and jakopter_stay().
Referenced by jakopter_slide_left_lua().
int jakopter_slide_right (float speed)
Command to make the drone slide to the right with a defined speed.
Parameters
speed the speed in percentage between 0 and 1
Returns
0 if success, -1 if command couldn't be set.
Definition at line 470 of file drone.c.
References jakopter_move(), and jakopter_stay().
Referenced by jakopter_slide_right_lua().
int jakopter_stay ()
Command to make the drone stay at its position.
Returns
0 if success, -1 if command couldn't be set.
Definition at line 429 of file drone.c.
References cmd_wait, HEAD_PCMD, and set_cmd().
Referenced by jakopter_backward(), jakopter_down(), jakopter_forward(), jakopter_rotate_left(), jakopter_rotate_right(), jakopter_slide_left(), jakopter_slide_right(), jakopter_stay_lua(), and jakopter_up().
int jakopter_switch_camera (unsigned int id)
Command to switch between front and bottom camera.
Parameters
id the id of the camera in video_channels enum:
0 horizontal
1 vertical
2 horizontal with vertical on left corner. Deprecated on ARdrone2
3 vertical with horizontal on left corner. Deprecated on ARdrone2
4 switch to the next camera
Returns
0 if success, -1 if command couldn't be set or id invalid.
Definition at line 306 of file drone.c.
References cmd_wait, HEAD_CONFIG, INT_LEN, set_cmd(), and VID_CHANNELS.
Referenced by jakopter_switch_camera_lua().
int jakopter_takeoff ()
Command to take off the drone.
Returns
0 if success, -1 if error.
Definition at line 344 of file drone.c.
References cmd_wait, HEAD_REF, HEIGHT_THRESHOLD, jakopter_flat_trim(), jakopter_height(), jakopter_is_flying(), NAVDATA_ATTEMPT, navdata_no_sq(), set_cmd(), and takeoff_arg.
Referenced by jakopter_takeoff_lua().
int jakopter_up (float speed)
Command to make the drone go up with a defined speed.
Parameters
speed the speed in percentage between 0 and 1
Returns
0 if success, -1 if command couldn't be set.
Definition at line 500 of file drone.c.
References jakopter_move(), and jakopter_stay().
Referenced by jakopter_up_lua().