Jakopter: include/video_decode.h File Reference
video_decode.h File Reference
#include <libavcodec/avcodec.h>
#include "video.h"
Macros
#define TCP_VIDEO_BUF_SIZE BASE_VIDEO_BUF_SIZE
#define JAKO_FFMPEG_LOG AV_LOG_PANIC
Functions
int video_init_decoder ()
int video_decode_packet (uint8_t *buffer, int buf_size, jakopter_video_frame_t *result)
void video_stop_decoder ()
Macro Definition Documentation
#define JAKO_FFMPEG_LOG AV_LOG_PANIC
Definition at line 19 of file video_decode.h.
Referenced by video_init_decoder().
#define TCP_VIDEO_BUF_SIZE BASE_VIDEO_BUF_SIZE
Definition at line 9 of file video_decode.h.
Referenced by video_routine().
Function Documentation
int video_decode_packet (uint8_t * buffer, int buf_size, jakopter_video_frame_t * result)
Decode a video buffer.
Returns
0 : buffer decoded, but no image produce (incomplete).
0 : decoded n images.
-1 : error while decoding.
Definition at line 80 of file video_decode.c.
References context, cpContext, current_frame, current_height, current_width, frameOffset, jakopter_video_frame_t::h, jakopter_video_frame_t::pixels, jakopter_video_frame_t::size, tempBuffer, tempBufferSize, video_alloc_frame_buffer(), video_packet, and jakopter_video_frame_t::w.
Referenced by video_routine().
int video_init_decoder ()
Definition at line 19 of file video_decode.c.
References codec, context, cpContext, current_frame, current_height, current_width, frameOffset, JAKO_FFMPEG_LOG, tempBuffer, tempBufferSize, and video_packet.
Referenced by jakopter_init_video().
void video_stop_decoder ()
Free the decoder and its associated structures.
Definition at line 140 of file video_decode.c.
References context, cpContext, current_frame, and tempBuffer.
Referenced by jakopter_init_video(), and video_clean().