Jakopter: src/network.c File Reference
network.c File Reference
#include <stdlib.h>
#include <stdbool.h>
#include <string.h>
#include <unistd.h>
#include <time.h>
#include <pthread.h>
#include <curl/curl.h>
#include <curl/easy.h>
#include "network.h"
Data Structures
struct CurlData
Functions
void * send_routine (void *args)
static size_t write_curl_to_com_channel (void *data, size_t size, size_t nmemb, void *userptr)
void * receive_routine (void *args)
int jakopter_init_network (const char *server_in, const char *server_out)
int jakopter_stop_network ()
Variables
jakopter_com_channel_t * network_in_channel
jakopter_com_channel_t * network_out_channel
pthread_t send_thread
pthread_t receive_thread
bool stopped_network = true
bool recv_ready = false
static char send_addr [256]
static char recv_addr [256]
Function Documentation
int jakopter_init_network (const char * server_in, const char * server_out)
Start the thread that listen on server_in and send data on server_out.
Parameters
server_in a HTTP address where Curl GET his data
server_out a HTTP address where Curl POST his data
Returns
0 OK, -1 otherwise
Definition at line 136 of file network.c.
References CHANNEL_INPUT_SIZE, CHANNEL_NETWORK_INPUT, CHANNEL_NETWORK_OUTPUT, CHANNEL_OUTPUT_SIZE, DEFAULT_CLIENT_IN, DEFAULT_CLIENT_OUT, jakopter_com_add_channel(), receive_routine(), receive_thread, recv_addr, recv_ready, send_addr, send_routine(), send_thread, and stopped_network.
Referenced by jakopter_init_network_lua().
int jakopter_stop_network ()
Stop curl.
Definition at line 184 of file network.c.
References CHANNEL_NETWORK_INPUT, CHANNEL_NETWORK_OUTPUT, jakopter_com_remove_channel(), receive_thread, recv_ready, send_thread, and stopped_network.
Referenced by jakopter_cleanup_lua(), and jakopter_stop_network_lua().
void* receive_routine (void * args)
Definition at line 103 of file network.c.
References recv_ready, stopped_network, TIMEOUT_NETWORK, and write_curl_to_com_channel().
Referenced by jakopter_init_network().
void* send_routine (void * args)
Definition at line 34 of file network.c.
References CHANNEL_OUTPUT_SIZE, jakopter_com_read_buf(), jakopter_com_read_float(), jakopter_com_read_int(), ORDER_SIZE, stopped_network, and TIMEOUT_NETWORK.
Referenced by jakopter_init_network().
static size_t write_curl_to_com_channel (void * data, size_t size, size_t nmemb, void * userptr) static
Definition at line 95 of file network.c.
References jakopter_com_write_buf(), and jakopter_com_write_int().
Referenced by receive_routine().
Variable Documentation
jakopter_com_channel_t* network_in_channel
Definition at line 13 of file network.c.
jakopter_com_channel_t* network_out_channel
Definition at line 15 of file network.c.
pthread_t receive_thread
Definition at line 18 of file network.c.
Referenced by jakopter_init_network(), and jakopter_stop_network().
char recv_addr[256] static
Definition at line 31 of file network.c.
Referenced by jakopter_init_network().
bool recv_ready = false
Definition at line 22 of file network.c.
Referenced by jakopter_init_network(), jakopter_stop_network(), and receive_routine().
char send_addr[256] static
Definition at line 30 of file network.c.
Referenced by jakopter_init_network().
pthread_t send_thread
Definition at line 17 of file network.c.
Referenced by jakopter_init_network(), and jakopter_stop_network().
bool stopped_network = true
Definition at line 20 of file network.c.
Referenced by jakopter_init_network(), jakopter_stop_network(), receive_routine(), and send_routine().