Jakopter: src/user_input.c File Reference
user_input.c File Reference
#include <stdio.h>
#include <stdbool.h>
#include <fcntl.h>
#include <pthread.h>
#include <unistd.h>
#include "user_input.h"
Functions
int read_cmd ()
int user_input_init ()
void * user_input_routine (void *args)
int user_input_connect ()
int user_input_disconnect ()
Variables
jakopter_com_channel_t * user_input_channel
pthread_t user_input_thread
bool stopped_user_input = true
static pthread_mutex_t mutex_user_input = PTHREAD_MUTEX_INITIALIZER
static pthread_mutex_t mutex_stopped_user_input = PTHREAD_MUTEX_INITIALIZER
Function Documentation
int read_cmd ()
Definition at line 19 of file user_input.c.
References CMDFILENAME, and mutex_user_input.
Referenced by user_input_routine().
int user_input_connect ()
Definition at line 82 of file user_input.c.
References CHANNEL_USERINPUT, jakopter_com_add_channel(), jakopter_com_write_int(), mutex_stopped_user_input, stopped_user_input, user_input_routine(), and user_input_thread.
Referenced by jakopter_connect().
int user_input_disconnect ()
Definition at line 115 of file user_input.c.
References CHANNEL_USERINPUT, jakopter_com_remove_channel(), mutex_stopped_user_input, stopped_user_input, and user_input_thread.
Referenced by jakopter_disconnect().
int user_input_init ()
Definition at line 42 of file user_input.c.
void* user_input_routine (void * args)
Definition at line 48 of file user_input.c.
References jakopter_com_write_int(), mutex_stopped_user_input, read_cmd(), stopped_user_input, and USERINPUT_INTERVAL.
Referenced by user_input_connect().
Variable Documentation
pthread_mutex_t mutex_stopped_user_input = PTHREAD_MUTEX_INITIALIZER static
Definition at line 17 of file user_input.c.
Referenced by user_input_connect(), user_input_disconnect(), and user_input_routine().
pthread_mutex_t mutex_user_input = PTHREAD_MUTEX_INITIALIZER static
Definition at line 16 of file user_input.c.
Referenced by read_cmd().
bool stopped_user_input = true
Definition at line 15 of file user_input.c.
Referenced by user_input_connect(), user_input_disconnect(), and user_input_routine().
jakopter_com_channel_t* user_input_channel
Definition at line 9 of file user_input.c.
pthread_t user_input_thread
Definition at line 13 of file user_input.c.
Referenced by user_input_connect(), and user_input_disconnect().