Jakopter: src/com_channel.c File Reference
com_channel.c File Reference
#include <stdlib.h>
#include <stdio.h>
#include <stddef.h>
#include <stdint.h>
#include <string.h>
#include <pthread.h>
#include <time.h>
#include "com_channel.h"
Data Structures
struct jakopter_com_channel_t
Functions
jakopter_com_channel_t * jakopter_com_create_channel (size_t size)
void jakopter_com_destroy_channel (jakopter_com_channel_t **cc)
JAKO_EXPORT void jakopter_com_write_int (jakopter_com_channel_t *cc, size_t offset, int value)
JAKO_EXPORT void jakopter_com_write_float (jakopter_com_channel_t *cc, size_t offset, float value)
JAKO_EXPORT void jakopter_com_write_char (jakopter_com_channel_t *cc, size_t offset, char value)
JAKO_EXPORT void jakopter_com_write_buf (jakopter_com_channel_t *cc, size_t offset, void *data, size_t size)
JAKO_EXPORT int jakopter_com_read_int (jakopter_com_channel_t *cc, size_t offset)
JAKO_EXPORT float jakopter_com_read_float (jakopter_com_channel_t *cc, size_t offset)
JAKO_EXPORT char jakopter_com_read_char (jakopter_com_channel_t *cc, size_t offset)
JAKO_EXPORT void * jakopter_com_read_buf (jakopter_com_channel_t *cc, size_t offset, size_t size, void *dest)
JAKO_EXPORT double jakopter_com_get_timestamp (jakopter_com_channel_t *cc)
Function Documentation
jakopter_com_channel_t* jakopter_com_create_channel (size_t size)
Initialize a com_channel structure, with the given buffer size.
Parameters
size Size of the communication buffer in bytes.
Returns
jakopter_com_channel_t structure, ready to be used. The structure should be freed with jakopter_destroy_com_channel once you're done using it. Returns NULL on failure.
Definition at line 26 of file com_channel.c.
References jakopter_com_channel_t::buf_size, jakopter_com_channel_t::buffer, jakopter_com_channel_t::init_time, jakopter_com_channel_t::last_write_time, and jakopter_com_channel_t::mutex.
Referenced by jakopter_com_add_channel().
void jakopter_com_destroy_channel (jakopter_com_channel_t ** cc)
Free the memory allocated for the given com channel structure.
Parameters
cc com channel to free. The pointer to the structure will be set to NULL on success.
Definition at line 58 of file com_channel.c.
Referenced by jakopter_com_remove_channel().
JAKO_EXPORT double jakopter_com_get_timestamp (jakopter_com_channel_t * cc)
Get the timestamp, in milliseconds, of the last write operation performed on a given com channel.
Parameters
cc com channel to check.
Definition at line 258 of file com_channel.c.
References jakopter_com_channel_t::init_time, jakopter_com_channel_t::last_write_time, and jakopter_com_channel_t::mutex.
Referenced by jakopter_com_get_timestamp_lua(), and video_display_process().
JAKO_EXPORT void* jakopter_com_read_buf (jakopter_com_channel_t * cc, size_t offset, size_t size, void * dest)
Read an arbitrary sequence of bytes.
Parameters
cc com channel to read from.
offset position of the data to be read in the channel's buffer.
size number of bytes to read.
dest buffer where the read data will be copied. Must point to a valid memory zone of at least size bytes.
Returns
dest.
Definition at line 235 of file com_channel.c.
References jakopter_com_channel_t::buf_size, jakopter_com_channel_t::buffer, and jakopter_com_channel_t::mutex.
Referenced by jakopter_com_read_string_lua(), and send_routine().
JAKO_EXPORT char jakopter_com_read_char (jakopter_com_channel_t * cc, size_t offset)
Definition at line 212 of file com_channel.c.
References jakopter_com_channel_t::buf_size, jakopter_com_channel_t::buffer, and jakopter_com_channel_t::mutex.
JAKO_EXPORT float jakopter_com_read_float (jakopter_com_channel_t * cc, size_t offset)
Definition at line 189 of file com_channel.c.
References jakopter_com_channel_t::buf_size, jakopter_com_channel_t::buffer, and jakopter_com_channel_t::mutex.
Referenced by jakopter_com_read_float_lua(), send_routine(), and update_infos().
JAKO_EXPORT int jakopter_com_read_int (jakopter_com_channel_t * cc, size_t offset)
Read from a com channel.
Parameters
cc the com_channel pointer
offset of the data to read in the channel.
Definition at line 166 of file com_channel.c.
References jakopter_com_channel_t::buf_size, jakopter_com_channel_t::buffer, and jakopter_com_channel_t::mutex.
Referenced by jakopter_com_read_int_lua(), jakopter_com_read_string_lua(), send_routine(), and update_infos().
JAKO_EXPORT void jakopter_com_write_buf (jakopter_com_channel_t * cc, size_t offset, void * data, size_t size)
Definition at line 139 of file com_channel.c.
References jakopter_com_channel_t::buf_size, jakopter_com_channel_t::buffer, jakopter_com_channel_t::last_write_time, and jakopter_com_channel_t::mutex.
Referenced by jakopter_com_write_string_lua(), and write_curl_to_com_channel().
JAKO_EXPORT void jakopter_com_write_char (jakopter_com_channel_t * cc, size_t offset, char value)
Definition at line 116 of file com_channel.c.
References jakopter_com_channel_t::buf_size, jakopter_com_channel_t::buffer, jakopter_com_channel_t::last_write_time, and jakopter_com_channel_t::mutex.
JAKO_EXPORT void jakopter_com_write_float (jakopter_com_channel_t * cc, size_t offset, float value)
Definition at line 94 of file com_channel.c.
References jakopter_com_channel_t::buf_size, jakopter_com_channel_t::buffer, jakopter_com_channel_t::last_write_time, and jakopter_com_channel_t::mutex.
Referenced by coords_routine(), jakopter_com_write_float_lua(), jakopter_init_coords(), and recv_cmd().
JAKO_EXPORT void jakopter_com_write_int (jakopter_com_channel_t * cc, size_t offset, int value)
Write to a com channel.
Parameters
cc the com_channel pointer
offset of the data to write in the channel.
value to be written at the given offset.
Definition at line 71 of file com_channel.c.
References jakopter_com_channel_t::buf_size, jakopter_com_channel_t::buffer, jakopter_com_channel_t::last_write_time, and jakopter_com_channel_t::mutex.
Referenced by jakopter_com_write_int_lua(), jakopter_com_write_string_lua(), recv_cmd(), user_input_connect(), user_input_routine(), video_display_process(), and write_curl_to_com_channel().