Jakopter: include/video.h File Reference
video.h File Reference
#include "common.h"
Data Structures
struct jakopter_video_frame_t
struct jakopter_frame_processing
struct jakopter_drawing
Macros
#define VIDEO_INTERVAL 1000000
#define VIDEO_TIMEOUT 4
#define BASE_VIDEO_BUF_SIZE 1024
#define PORT_VIDEO 5555
Functions
int jakopter_draw_icon (const char *p, int x, int y, int w, int h)
int jakopter_draw_text (const char *s, int x, int y)
void jakopter_draw_remove (int id)
void jakopter_draw_resize (int id, int width, int height)
void jakopter_draw_move (int id, int x, int y)
void jakopter_set_callback (int id)
int jakopter_init_video ()
int jakopter_stop_video ()
int video_set_stopped ()
int video_is_stopped ()
Macro Definition Documentation
#define BASE_VIDEO_BUF_SIZE 1024
Definition at line 10 of file video.h.
Referenced by video_routine().
#define PORT_VIDEO 5555
Definition at line 11 of file video.h.
Referenced by jakopter_init_video().
#define VIDEO_INTERVAL 1000000
Definition at line 8 of file video.h.
Referenced by video_routine().
#define VIDEO_TIMEOUT 4
Definition at line 9 of file video.h.
Referenced by video_routine().
Function Documentation
int jakopter_draw_icon (const char * p, int x, int y, int w, int h)
Definition at line 256 of file video.c.
References jakopter_drawing::draw_icon.
Referenced by jakopter_draw_icon_lua().
void jakopter_draw_move (int id, int x, int y)
Definition at line 283 of file video.c.
References jakopter_drawing::move.
Referenced by jakopter_draw_move_lua().
void jakopter_draw_remove (int id)
Definition at line 270 of file video.c.
References jakopter_drawing::remove.
Referenced by jakopter_draw_remove_lua().
void jakopter_draw_resize (int id, int width, int height)
Definition at line 277 of file video.c.
References jakopter_drawing::resize.
Referenced by jakopter_draw_resize_lua().
int jakopter_draw_text (const char * s, int x, int y)
Definition at line 263 of file video.c.
References jakopter_drawing::draw_text.
Referenced by jakopter_draw_text_lua().
int jakopter_init_video ()
Start the thread which receive video packets on port 5555
Referenced by jakopter_init_video_lua().
void jakopter_set_callback (int id)
Definition at line 249 of file video.c.
References jakopter_frame_processing::set_callback.
Referenced by jakopter_set_callback_lua().
int jakopter_stop_video ()
Definition at line 237 of file video.c.
References video_join_thread(), and video_set_stopped().
Referenced by jakopter_cleanup_lua(), and jakopter_stop_video_lua().
int video_is_stopped ()
helper for mutex-protected value
Definition at line 297 of file video.c.
References mutex_stopped, and stopped.
Referenced by processing_routine(), video_routine(), and video_set_stopped().
int video_set_stopped ()
Ask the video thread to stop without joining with it. Shouldn't be called by user. Useful for stopping it from the inside.
Returns
0 if stopped was 0, 1 if it wasn't.
Definition at line 305 of file video.c.
References stopped, and video_is_stopped().
Referenced by jakopter_dumpFrameToFile(), jakopter_stop_video(), processing_routine(), and video_routine().