Jakopter: src/video.c File Reference
video.c File Reference
#include "video.h"
#include "video_queue.h"
#include "video_decode.h"
#include "video_display.h"
#include "visp.h"
Functions
static void video_clean ()
static int video_join_thread ()
void * video_routine (void *args)
void * processing_routine (void *args)
JAKO_EXPORT int jakopter_init_video (const char *drone_ip)
JAKO_EXPORT int jakopter_stop_video ()
JAKO_EXPORT void jakopter_set_callback (int id)
JAKO_EXPORT int jakopter_draw_icon (const char *p, int x, int y, int w, int h)
JAKO_EXPORT int jakopter_draw_text (const char *s, int x, int y)
JAKO_EXPORT void jakopter_draw_remove (int id)
JAKO_EXPORT void jakopter_draw_resize (int id, int width, int height)
JAKO_EXPORT void jakopter_draw_move (int id, int x, int y)
int video_is_stopped ()
int video_set_stopped ()
Variables
struct sockaddr_in addr_drone_video addr_client_video
int sock_video
pthread_t video_thread
pthread_t processing_thread
fd_set vid_fd_set
struct timeval video_timeout = {VIDEO_TIMEOUT, 0}
struct timespec video_interval = {0, VIDEO_INTERVAL}
static const struct jakopter_frame_processing frame_process
static const struct jakopter_drawing draw_implementation
static volatile int stopped = 1
static pthread_mutex_t mutex_stopped = PTHREAD_MUTEX_INITIALIZER
static volatile int terminated = 1
static pthread_mutex_t mutex_terminated = PTHREAD_MUTEX_INITIALIZER
Function Documentation
JAKO_EXPORT int jakopter_draw_icon (const char * p, int x, int y, int w, int h)
Definition at line 256 of file video.c.
References jakopter_drawing::draw_icon.
Referenced by jakopter_draw_icon_lua().
JAKO_EXPORT void jakopter_draw_move (int id, int x, int y)
Definition at line 283 of file video.c.
References jakopter_drawing::move.
Referenced by jakopter_draw_move_lua().
JAKO_EXPORT void jakopter_draw_remove (int id)
Definition at line 270 of file video.c.
References jakopter_drawing::remove.
Referenced by jakopter_draw_remove_lua().
JAKO_EXPORT void jakopter_draw_resize (int id, int width, int height)
Definition at line 277 of file video.c.
References jakopter_drawing::resize.
Referenced by jakopter_draw_resize_lua().
JAKO_EXPORT int jakopter_draw_text (const char * s, int x, int y)
Definition at line 263 of file video.c.
References jakopter_drawing::draw_text.
Referenced by jakopter_draw_text_lua().
JAKO_EXPORT int jakopter_init_video (const char * drone_ip)
Definition at line 154 of file video.c.
References jakopter_frame_processing::init, mutex_stopped, PORT_VIDEO, processing_routine(), processing_thread, sock_video, stopped, terminated, vid_fd_set, video_clean(), video_init_decoder(), video_join_thread(), video_queue_init(), video_routine(), video_stop_decoder(), video_thread, and WIFI_ARDRONE_IP.
JAKO_EXPORT void jakopter_set_callback (int id)
Definition at line 249 of file video.c.
References jakopter_frame_processing::set_callback.
Referenced by jakopter_set_callback_lua().
JAKO_EXPORT int jakopter_stop_video ()
Definition at line 237 of file video.c.
References video_join_thread(), and video_set_stopped().
Referenced by jakopter_cleanup_lua(), and jakopter_stop_video_lua().
void* processing_routine (void * args)
Definition at line 130 of file video.c.
References jakopter_frame_processing::callback, jakopter_frame_processing::clean, jakopter_video_frame_t::h, jakopter_video_frame_t::pixels, jakopter_video_frame_t::size, video_is_stopped(), video_queue_pull_frame(), video_set_stopped(), and jakopter_video_frame_t::w.
Referenced by jakopter_init_video().
void video_clean () static
Definition at line 289 of file video.c.
References sock_video, video_queue_free(), and video_stop_decoder().
Referenced by jakopter_init_video(), and video_routine().
int video_is_stopped ()
helper for mutex-protected value
Definition at line 297 of file video.c.
References mutex_stopped, and stopped.
Referenced by processing_routine(), video_routine(), and video_set_stopped().
int video_join_thread () static
Join with the video thread (don't ask it to stop though). If it's already terminated, do nothing.
Returns
the thread's termination status when entering the function. (0 if it was running, 1 if it wasn't), -1 if joining fails.
Definition at line 321 of file video.c.
References mutex_terminated, terminated, and video_thread.
Referenced by jakopter_init_video(), and jakopter_stop_video().
void* video_routine (void * args)
Definition at line 64 of file video.c.
References BASE_VIDEO_BUF_SIZE, processing_thread, sock_video, TCP_VIDEO_BUF_SIZE, vid_fd_set, video_clean(), video_decode_packet(), VIDEO_INTERVAL, video_interval, video_is_stopped(), VIDEO_QUEUE_END, video_queue_push_frame(), video_set_stopped(), VIDEO_TIMEOUT, and video_timeout.
Referenced by jakopter_init_video().
int video_set_stopped ()
Ask the video thread to stop without joining with it. Shouldn't be called by user. Useful for stopping it from the inside.
Returns
0 if stopped was 0, 1 if it wasn't.
Definition at line 305 of file video.c.
References stopped, and video_is_stopped().
Referenced by jakopter_dumpFrameToFile(), jakopter_stop_video(), processing_routine(), and video_routine().
Variable Documentation
struct sockaddr_in addr_drone_video addr_client_video
Definition at line 8 of file video.c.
const struct jakopter_drawing draw_implementation static
Initial value:
= {
    .draw_icon   = NULL,
    .draw_text   = NULL,
    .remove      = NULL,
    .resize      = NULL,
    .move        = NULL
}
Drawing API implementation
Definition at line 34 of file video.c.
const struct jakopter_frame_processing frame_process static
Initial value:
= {
    .callback = visp_process,
    .init     = visp_init,
    .clean    = visp_destroy,
    .set_callback = visp_set_process
}
Video processing API implementation
Definition at line 19 of file video.c.
pthread_mutex_t mutex_stopped = PTHREAD_MUTEX_INITIALIZER static
Definition at line 52 of file video.c.
Referenced by jakopter_init_video(), and video_is_stopped().
pthread_mutex_t mutex_terminated = PTHREAD_MUTEX_INITIALIZER static
Definition at line 56 of file video.c.
Referenced by video_join_thread().
pthread_t processing_thread
Definition at line 12 of file video.c.
Referenced by jakopter_init_video(), and video_routine().
int sock_video
Definition at line 9 of file video.c.
Referenced by jakopter_init_video(), video_clean(), and video_routine().
volatile int stopped = 1 static
Definition at line 51 of file video.c.
Referenced by jakopter_init_video(), video_is_stopped(), and video_set_stopped().
volatile int terminated = 1 static
Definition at line 55 of file video.c.
Referenced by jakopter_init_video(), and video_join_thread().
fd_set vid_fd_set
Definition at line 14 of file video.c.
Referenced by jakopter_init_video(), and video_routine().
struct timespec video_interval = {0, VIDEO_INTERVAL}
Definition at line 16 of file video.c.
Referenced by video_routine().
pthread_t video_thread
Definition at line 12 of file video.c.
Referenced by jakopter_init_video(), and video_join_thread().
struct timeval video_timeout = {VIDEO_TIMEOUT, 0}
Definition at line 15 of file video.c.
Referenced by video_routine().