Jakopter: jakopter_drawing Struct Reference
jakopter_drawing Struct Reference
#include <video.h>
Data Fields
int(* draw_icon)(const char *path, int x, int y, int width, int height)
int(* draw_text)(const char *string, int x, int y)
void(* remove)(int id)
void(* resize)(int id, int width, int height)
void(* move)(int id, int x, int y)
Detailed Description
Drawing API
Definition at line 52 of file video.h.
Field Documentation
int(* jakopter_drawing::draw_icon) (const char *path, int x, int y, int width, int height)
incrust an image on the frame
Parameters
path the path from the jakopter current working directory
x horizontal position in pixels
y vertical position in pixels
width desired width for this icon in pixels
height desired height for this icon in pixels
Returns
an id use to manipulate this icon
Definition at line 61 of file video.h.
Referenced by jakopter_draw_icon().
int(* jakopter_drawing::draw_text) (const char *string, int x, int y)
incrust a text on the frame. There is interlacing if you delete then create the text just after.
Parameters
path the path from the jakopter current working directory
x horizontal position in pixels
y vertical position in pixels
Definition at line 72 of file video.h.
Referenced by jakopter_draw_text().
void(* jakopter_drawing::move) (int id, int x, int y)
move a graphic element. Can be NULL.
Parameters
the id of the graphic element
x horizontal position in pixels
y vertical position in pixels
Definition at line 92 of file video.h.
Referenced by jakopter_draw_move().
void(* jakopter_drawing::remove) (int id)
remove a graphic element
Parameters
the id of the graphic element
Definition at line 78 of file video.h.
Referenced by jakopter_draw_remove().
void(* jakopter_drawing::resize) (int id, int width, int height)
resize a graphic element. Can be NULL.
Parameters
the id of the graphic element
width desired width for this icon in pixels
height desired height for this icon in pixels
Definition at line 84 of file video.h.
Referenced by jakopter_draw_resize().