Jakopter: src/com_master.c File Reference
com_master.c File Reference
#include <stdbool.h>
#include <stdio.h>
#include <pthread.h>
#include "com_master.h"
#include "utils.h"
Functions
int jakopter_com_init_master (int nb_chan_max)
int jakopter_com_master_is_init ()
JAKO_EXPORT jakopter_com_channel_t * jakopter_com_add_channel (int id, size_t size)
JAKO_EXPORT jakopter_com_channel_t * jakopter_com_get_channel (int id)
JAKO_EXPORT int jakopter_com_remove_channel (int id)
void jakopter_com_destroy_master ()
Variables
static bool isInitialized = true
static jakopter_com_channel_t * master [NB_CHANNELS] = {NULL}
static pthread_mutex_t master_mutex = PTHREAD_MUTEX_INITIALIZER
static int nb_max_chan = NB_CHANNELS
Function Documentation
JAKO_EXPORT jakopter_com_channel_t* jakopter_com_add_channel (int id, size_t size)
Create a channel and index it in the master list.
Parameters
id identificator of the channel to be created. Should be between 1 and NB_CHANNELS (excluded). Shouldn't be the id of a currently active channel.
size Size of the new channel in bytes.
Returns
a pointer to the new channel, that can be used with read/write functions. NULL if there was an error.
Definition at line 48 of file com_master.c.
References jakopter_com_create_channel(), master_mutex, and nb_max_chan.
Referenced by jakopter_init_coords(), jakopter_init_network(), navdata_connect(), user_input_connect(), and video_display_init().
void jakopter_com_destroy_master ()
Definition at line 109 of file com_master.c.
JAKO_EXPORT jakopter_com_channel_t* jakopter_com_get_channel (int id)
Look up the given id in the master channel and return the corresponding channel.
Parameters
id identificator of the channel. It should belong to the jakopter_channels enum.
Returns
a pointer to the requested channel, ready to be used with read/write com_channel functions. NULL if the requested channel doesn't exist.
Definition at line 72 of file com_master.c.
References nb_max_chan.
Referenced by jakopter_com_get_timestamp_lua(), jakopter_com_read_float_lua(), jakopter_com_read_int_lua(), jakopter_com_read_string_lua(), jakopter_com_remove_channel(), jakopter_com_write_float_lua(), jakopter_com_write_int_lua(), and jakopter_com_write_string_lua().
int jakopter_com_init_master (int nb_chan_max)
Definition at line 24 of file com_master.c.
int jakopter_com_master_is_init ()
Definition at line 43 of file com_master.c.
References isInitialized.
JAKO_EXPORT int jakopter_com_remove_channel (int id)
Remove the requested channel from the master index, and free its resources.
Parameters
id identificator of the channel to be deleted.
Returns
0 on success, -1 if the channel doesn't exist.
Definition at line 90 of file com_master.c.
References jakopter_com_destroy_channel(), jakopter_com_get_channel(), and master_mutex.
Referenced by jakopter_stop_coords(), jakopter_stop_network(), navdata_disconnect(), user_input_disconnect(), and video_display_destroy().
Variable Documentation
bool isInitialized = true static
Definition at line 10 of file com_master.c.
Referenced by jakopter_com_master_is_init().
jakopter_com_channel_t* master[NB_CHANNELS] = {NULL} static
Definition at line 13 of file com_master.c.
pthread_mutex_t master_mutex = PTHREAD_MUTEX_INITIALIZER static
Definition at line 17 of file com_master.c.
Referenced by jakopter_com_add_channel(), and jakopter_com_remove_channel().
int nb_max_chan = NB_CHANNELS static
Definition at line 21 of file com_master.c.
Referenced by jakopter_com_add_channel(), and jakopter_com_get_channel().