Jakopter: include/video_display.h File Reference
video_display.h File Reference
#include "com_master.h"
#include "utils.h"
Macros
#define FONT_PATH "../../resources/FreeSans.ttf"
#define DISPLAY_COM_IN_SIZE 32
#define VIDEO_ICON 1
#define VIDEO_TEXT 2
#define DISPLAY_CYCLES 1
Enumerations
enum video_nav_infos { VIDEO_BAT, VIDEO_ALT, VIDEO_NB_NAV_INFOS }
Functions
int video_display_process (uint8_t *frame, int width, int height, int size)
int video_display_init ()
void video_display_destroy ()
int display_draw_icon (const char *path, int x, int y, int width, int height)
int display_draw_text (const char *string, int x, int y)
void display_graphic_remove (int id)
void display_graphic_resize (int id, int width, int height)
void display_graphic_move (int id, int x, int y)
Macro Definition Documentation
#define DISPLAY_COM_IN_SIZE 32
Definition at line 9 of file video_display.h.
Referenced by video_display_init().
#define DISPLAY_CYCLES 1
Definition at line 71 of file video_display.h.
Referenced by display_graphic_remove().
#define FONT_PATH "../../resources/FreeSans.ttf"
Definition at line 7 of file video_display.h.
Referenced by video_display_init_size().
#define VIDEO_ICON 1
Navdata values that are going to be received by the display module.
Definition at line 69 of file video_display.h.
Referenced by display_draw_icon(), and load_element().
#define VIDEO_TEXT 2
Definition at line 70 of file video_display.h.
Referenced by display_draw_text(), and load_element().
Enumeration Type Documentation
enum video_nav_infos
Enumerator
VIDEO_BAT
VIDEO_ALT
VIDEO_NB_NAV_INFOS
Definition at line 72 of file video_display.h.
Function Documentation
int display_draw_icon (const char * path, int x, int y, int width, int height)
Draw an icon on the video display. width and height are facultative, set it to 0.
Parameters
path the relative path to the icon
x in pixels from left
y in pixels from top
width in pixels, optional
height in pixels, optional
Returns
the icon id
Definition at line 639 of file video_display.c.
References current_height, current_width, graphics_list::graphic, graphic_append(), graphics_list::id, mutex_graphics_list, graphics_t::pos, graphics_list::string, graphics_t::tex, video_graphic_create(), and VIDEO_ICON.
int display_draw_text (const char * string, int x, int y)
Draw a string on the video display.
Parameters
string the text to print
x in pixels from left
y in pixels from top
Returns
the icon id
Definition at line 677 of file video_display.c.
References graphics_list::graphic, graphic_append(), graphics_list::id, mutex_graphics_list, graphics_t::pos, graphics_list::string, graphics_t::tex, video_graphic_create(), and VIDEO_TEXT.
void display_graphic_move (int id, int x, int y)
Move a graphic element on the display window.
Parameters
id the id returned by display_draw_...
x in pixels from left
y in pixels from top
Definition at line 753 of file video_display.c.
References current_height, current_width, graphics_list::graphic, icon_registry, graphics_list::id, initialized, mutex_graphics_list, graphics_list::next, and graphics_t::pos.
void display_graphic_remove (int id)
Free the memory associated with the graphic element.
Definition at line 704 of file video_display.c.
References DISPLAY_CYCLES, icon_registry, graphics_list::id, mutex_graphics_list, graphics_list::next, and graphics_list::time_to_live.
Referenced by load_element().
void display_graphic_resize (int id, int width, int height)
Resize a graphic element on the display window.
Parameters
id the id returned by display_draw_...
width in pixels
height in pixels
Definition at line 730 of file video_display.c.
References current_height, current_width, graphics_list::graphic, icon_registry, graphics_list::id, mutex_graphics_list, graphics_list::next, and graphics_t::pos.
void video_display_destroy ()
Free the memory associated with the module. Clean the display context : close the window and clean SDL structures.
Definition at line 252 of file video_display.c.
References CHANNEL_DISPLAY, frameTex, icon_registry, initialized, jakopter_com_remove_channel(), mutex_graphics_list, graphics_list::next, renderer, video_clean_text(), video_graphic_destroy(), VIDEO_NB_NAV_INFOS, and win.
Referenced by video_display_process().
int video_display_init ()
Create the com_channel needed to communicate with the display module.
Definition at line 240 of file video_display.c.
References CHANNEL_DISPLAY, DISPLAY_COM_IN_SIZE, jakopter_com_add_channel(), and prev_update.
int video_display_process (uint8_t * frame, int width, int height, int size)
"Got frame" callback. Fills the texture with the given frame, and displays it on the window.
Definition at line 323 of file video_display.c.
References current_height, current_width, draw_attitude_indic(), draw_compass(), frameTex, graphics_list::graphic, icon_registry, initialized, jakopter_com_get_timestamp(), jakopter_com_write_int(), load_element(), mutex_graphics_list, graphics_list::next, graphics_t::pos, prev_update, renderer, take_screenshot(), graphics_t::tex, unload_element(), update_infos(), video_display_destroy(), video_display_init_size(), video_display_set_size(), VIDEO_NB_NAV_INFOS, and want_screenshot.