Jakopter: jakopter_frame_processing Struct Reference
jakopter_frame_processing Struct Reference
#include <video.h>
Data Fields
int(* callback)(uint8_t *frame, int width, int height, int size)
int(* init)(void)
void(* clean)(void)
void(* set_callback)(int id)
Detailed Description
Video processing API
Definition at line 25 of file video.h.
Field Documentation
int(* jakopter_frame_processing::callback) (uint8_t *frame, int width, int height, int size)
callback to which is sent every decoded frame.
Parameters
frame buffer containing the raw frame data, encoded in YUV420p. A value of NULL for this parameter means the video stream has ended.
width frame width
height frame height
size size of the buffer in bytes
Returns
the return value of the callback will be checked by the decoding routine. LESS THAN 0 : the video thread will stop. Anything else : no effect.
Definition at line 36 of file video.h.
Referenced by processing_routine().
void(* jakopter_frame_processing::clean) (void)
Definition at line 44 of file video.h.
Referenced by processing_routine().
int(* jakopter_frame_processing::init) (void)
initialize and clean the processing module used by the callback, if needed. Can be NULL.
Definition at line 43 of file video.h.
Referenced by jakopter_init_video().
void(* jakopter_frame_processing::set_callback) (int id)
Allow to choose between different callbacks at runtime Can be NULL.
Definition at line 48 of file video.h.
Referenced by jakopter_set_callback().