Jakopter: src/drone.c File Reference
drone.c File Reference
#include <time.h>
#include "common.h"
#include "drone.h"
#include "navdata.h"
#include "user_input.h"
Macros
#define LOG_LEN TSTAMP_LEN+PACKET_SIZE
Functions
static int set_cmd (char *cmd_type, char **args, int nb_args)
static int send_cmd ()
int init_navdata_bootstrap ()
int config_ack ()
void * cmd_routine (void *args)
JAKO_EXPORT int jakopter_connect (const char *drone_ip)
JAKO_EXPORT int jakopter_disconnect ()
JAKO_EXPORT int jakopter_flat_trim ()
JAKO_EXPORT int jakopter_calib ()
JAKO_EXPORT int jakopter_switch_camera (unsigned int id)
JAKO_EXPORT int jakopter_reinit ()
JAKO_EXPORT int jakopter_takeoff ()
JAKO_EXPORT int jakopter_land ()
JAKO_EXPORT int jakopter_emergency ()
JAKO_EXPORT int jakopter_stay ()
JAKO_EXPORT int jakopter_rotate_left (float speed)
JAKO_EXPORT int jakopter_rotate_right (float speed)
JAKO_EXPORT int jakopter_slide_left (float speed)
JAKO_EXPORT int jakopter_slide_right (float speed)
JAKO_EXPORT int jakopter_forward (float speed)
JAKO_EXPORT int jakopter_backward (float speed)
JAKO_EXPORT int jakopter_up (float speed)
JAKO_EXPORT int jakopter_down (float speed)
JAKO_EXPORT int jakopter_move (float l_to_r, float b_to_f, float vertical_speed, float angular_speed)
JAKO_EXPORT const char * jakopter_log_command ()
Variables
static char command [PACKET_SIZE]
static char command_logged [LOG_LEN]
static char * takeoff_arg = "290718208"
static char * land_arg = "290717696"
static char * emergency_arg = "290717952"
static int cmd_no_sq = 0
static char * command_type = NULL
static char command_args [ARGS_MAX][ARG_LEN]
static struct timespec cmd_wait = {0, NAVDATA_ATTEMPT*TIMEOUT_CMD}
pthread_t cmd_thread
volatile int stopped = 1
static pthread_mutex_t mutex_cmd = PTHREAD_MUTEX_INITIALIZER
static pthread_mutex_t mutex_stopped = PTHREAD_MUTEX_INITIALIZER
Macro Definition Documentation
#define LOG_LEN TSTAMP_LEN+PACKET_SIZE
Definition at line 8 of file drone.c.
Referenced by jakopter_log_command(), and send_cmd().
Function Documentation
void* cmd_routine (void * args)
This cmd_thread function is a timer which send a command each TIMEOUT_CMD ns.
Parameters
args not used
Definition at line 160 of file drone.c.
References mutex_stopped, send_cmd(), stopped, and TIMEOUT_CMD.
Referenced by jakopter_connect().
int config_ack ()
Command used by navdata to acknowledge navdata settings.
Returns
send return code or -1 if command couldn't be set.
Definition at line 137 of file drone.c.
References cmd_wait, HEAD_CTRL, send_cmd(), and set_cmd().
Referenced by navdata_init().
int init_navdata_bootstrap ()
Command used by navdata to define the type of navdata to "demo".
Returns
send return code or -1 if command couldn't be set.
Definition at line 120 of file drone.c.
References cmd_wait, HEAD_CONFIG, send_cmd(), and set_cmd().
Referenced by navdata_init().
JAKO_EXPORT int jakopter_backward (float speed)
Command to make the drone go backward with a defined speed.
Parameters
speed the speed in percentage between 0 and 1
Returns
0 if success, -1 if command couldn't be set.
Definition at line 490 of file drone.c.
References jakopter_move(), and jakopter_stay().
Referenced by jakopter_backward_lua().
JAKO_EXPORT int jakopter_calib ()
Calibration of the drone for smartphone accelerometer.
Returns
0 if success, -1 if the drone isn't flying or the command couldn't be set.
Definition at line 286 of file drone.c.
References cmd_wait, HEAD_CALIB, jakopter_is_flying(), and set_cmd().
Referenced by jakopter_calib_lua().
JAKO_EXPORT int jakopter_connect (const char * drone_ip)
Creates a socket and starts the command thread. Needs the computer to be connected to the drone wifi network.
Parameters
drone_ip used by simulator, if you are with a real drone, set it to NULL. 255.255.255.255 can't be used (see man inet_addr)
Returns
0 if success, -1 if error
Definition at line 181 of file drone.c.
References addr_client, cmd_no_sq, cmd_routine(), cmd_thread, command_logged, command_type, INT_LEN, mutex_cmd, mutex_stopped, navdata_connect(), PACKET_SIZE, PORT_CMD, sock_cmd, stopped, user_input_connect(), and WIFI_ARDRONE_IP.
Referenced by jakopter_connect_lua().
JAKO_EXPORT int jakopter_disconnect ()
Stop main thread (End of drone connection)
Returns
pthread_join value or -1 if the communication is already stopped
Definition at line 252 of file drone.c.
References cmd_thread, mutex_stopped, navdata_disconnect(), sock_cmd, stopped, and user_input_disconnect().
Referenced by jakopter_cleanup_lua(), and jakopter_disconnect_lua().
JAKO_EXPORT int jakopter_down (float speed)
Command to make the drone go down with a defined speed.
Parameters
speed the speed in percentage between 0 and 1
Returns
0 if success, -1 if command couldn't be set.
Definition at line 510 of file drone.c.
References jakopter_move(), and jakopter_stay().
Referenced by jakopter_down_lua().
JAKO_EXPORT int jakopter_emergency ()
Command to stop drone rotors.
Returns
0 if success, -1 if command couldn't be set.
Definition at line 415 of file drone.c.
References cmd_wait, emergency_arg, HEAD_REF, and set_cmd().
Referenced by jakopter_emergency_lua(), and jakopter_land().
JAKO_EXPORT int jakopter_flat_trim ()
Set the frame of reference of the drone before taking off.
Returns
0 if success, -1 if the drone is flying or the command couldn't be set.
Definition at line 269 of file drone.c.
References cmd_wait, HEAD_FTRIM, jakopter_is_flying(), and set_cmd().
Referenced by jakopter_ftrim_lua(), and jakopter_takeoff().
JAKO_EXPORT int jakopter_forward (float speed)
Command to make the drone go forward with a defined speed.
Parameters
speed the speed in percentage between 0 and 1
Returns
0 if success, -1 if command couldn't be set.
Definition at line 480 of file drone.c.
References jakopter_move(), and jakopter_stay().
Referenced by jakopter_forward_lua().
JAKO_EXPORT int jakopter_land ()
Command to land the drone. If no recent navdata are received, it sends the emergency command.
Returns
0 if success, -1 if error.
Definition at line 381 of file drone.c.
References cmd_wait, HEAD_REF, HEIGHT_THRESHOLD, jakopter_emergency(), jakopter_height(), jakopter_is_flying(), land_arg, NAVDATA_ATTEMPT, navdata_no_sq(), and set_cmd().
Referenced by jakopter_cleanup_lua(), and jakopter_land_lua().
JAKO_EXPORT const char* jakopter_log_command ()
Return a timestamp and the last command sent separated with a colon.
Returns
the last logged_command if connected, NULL otherwise.
Definition at line 553 of file drone.c.
References command_logged, LOG_LEN, mutex_cmd, and stopped.
Referenced by jakopter_log_command_lua().
JAKO_EXPORT int jakopter_move (float l_to_r, float b_to_f, float vertical_speed, float angular_speed)
define the movement of the drone (-1.0 to 1.0 values).
Parameters
l_to_r the speed from left to right
b_to_f the speed from backward to forward
vertical_speed the speed from down to up
angular_speed the angular speed to rotate the drone
Returns
0 if success, -1 if command couldn't be set.
Definition at line 520 of file drone.c.
References cmd_wait, HEAD_PCMD, INT_LEN, and set_cmd().
Referenced by jakopter_backward(), jakopter_down(), jakopter_forward(), jakopter_move_lua(), jakopter_rotate_left(), jakopter_rotate_right(), jakopter_slide_left(), jakopter_slide_right(), and jakopter_up().
JAKO_EXPORT int jakopter_reinit ()
Command to reset the communication watchdog.
Returns
0 if success, -1 if command couldn't be set.
Definition at line 331 of file drone.c.
References cmd_wait, HEAD_COM_WATCHDOG, and set_cmd().
Referenced by jakopter_reinit_lua().
JAKO_EXPORT int jakopter_rotate_left (float speed)
Command to make the drone rotate to the left with an angular speed.
Parameters
speed the angular speed in percentage between 0 and 1
Returns
0 if success, -1 if command couldn't be set.
Definition at line 440 of file drone.c.
References jakopter_move(), and jakopter_stay().
Referenced by jakopter_rotate_left_lua().
JAKO_EXPORT int jakopter_rotate_right (float speed)
Command to make the drone rotate to the right with an angular speed.
Parameters
speed the angular speed in percentage between 0 and 1
Returns
0 if success, -1 if command couldn't be set.
Definition at line 450 of file drone.c.
References jakopter_move(), and jakopter_stay().
Referenced by jakopter_rotate_right_lua().
JAKO_EXPORT int jakopter_slide_left (float speed)
Command to make the drone slide to the left with a defined speed.
Parameters
speed the speed in percentage between 0 and 1
Returns
0 if success, -1 if command couldn't be set.
Definition at line 460 of file drone.c.
References jakopter_move(), and jakopter_stay().
Referenced by jakopter_slide_left_lua().
JAKO_EXPORT int jakopter_slide_right (float speed)
Command to make the drone slide to the right with a defined speed.
Parameters
speed the speed in percentage between 0 and 1
Returns
0 if success, -1 if command couldn't be set.
Definition at line 470 of file drone.c.
References jakopter_move(), and jakopter_stay().
Referenced by jakopter_slide_right_lua().
JAKO_EXPORT int jakopter_stay ()
Command to make the drone stay at its position.
Returns
0 if success, -1 if command couldn't be set.
Definition at line 429 of file drone.c.
References cmd_wait, HEAD_PCMD, and set_cmd().
Referenced by jakopter_backward(), jakopter_down(), jakopter_forward(), jakopter_rotate_left(), jakopter_rotate_right(), jakopter_slide_left(), jakopter_slide_right(), jakopter_stay_lua(), and jakopter_up().
JAKO_EXPORT int jakopter_switch_camera (unsigned int id)
Command to switch between front and bottom camera.
Parameters
id the id of the camera in video_channels enum:
0 horizontal
1 vertical
2 horizontal with vertical on left corner. Deprecated on ARdrone2
3 vertical with horizontal on left corner. Deprecated on ARdrone2
4 switch to the next camera
Returns
0 if success, -1 if command couldn't be set or id invalid.
Definition at line 306 of file drone.c.
References cmd_wait, HEAD_CONFIG, INT_LEN, set_cmd(), and VID_CHANNELS.
Referenced by jakopter_switch_camera_lua().
JAKO_EXPORT int jakopter_takeoff ()
Command to take off the drone.
Returns
0 if success, -1 if error.
Definition at line 344 of file drone.c.
References cmd_wait, HEAD_REF, HEIGHT_THRESHOLD, jakopter_flat_trim(), jakopter_height(), jakopter_is_flying(), NAVDATA_ATTEMPT, navdata_no_sq(), set_cmd(), and takeoff_arg.
Referenced by jakopter_takeoff_lua().
JAKO_EXPORT int jakopter_up (float speed)
Command to make the drone go up with a defined speed.
Parameters
speed the speed in percentage between 0 and 1
Returns
0 if success, -1 if command couldn't be set.
Definition at line 500 of file drone.c.
References jakopter_move(), and jakopter_stay().
Referenced by jakopter_up_lua().
static int send_cmd () static
Send the current command stored in command_type.
Returns
sendto return code or 0 if nothing sent
Definition at line 69 of file drone.c.
References ARG_LEN, ARGS_MAX, cmd_no_sq, command, command_args, command_logged, command_type, HEAD_LEN, INT_LEN, LOG_LEN, mutex_cmd, PACKET_SIZE, sock_cmd, and TSTAMP_LEN.
Referenced by cmd_routine(), config_ack(), and init_navdata_bootstrap().
static int set_cmd (char * cmd_type, char ** args, int nb_args) static
Change the current command sent.
Parameters
cmd_type header like SOMETHING corresponding to AT*SOMETHING
args arguments of the command
nb_args number of arguments
Returns
-1 if nb_args greater than the max number of arguments
Definition at line 44 of file drone.c.
References ARG_LEN, ARGS_MAX, command_args, command_type, and mutex_cmd.
Referenced by config_ack(), init_navdata_bootstrap(), jakopter_calib(), jakopter_emergency(), jakopter_flat_trim(), jakopter_land(), jakopter_move(), jakopter_reinit(), jakopter_stay(), jakopter_switch_camera(), and jakopter_takeoff().
Variable Documentation
int cmd_no_sq = 0 static
Definition at line 20 of file drone.c.
Referenced by jakopter_connect(), and send_cmd().
pthread_t cmd_thread
Definition at line 29 of file drone.c.
Referenced by jakopter_connect(), and jakopter_disconnect().
struct timespec cmd_wait = {0, NAVDATA_ATTEMPT*TIMEOUT_CMD} static
Definition at line 26 of file drone.c.
Referenced by config_ack(), init_navdata_bootstrap(), jakopter_calib(), jakopter_emergency(), jakopter_flat_trim(), jakopter_land(), jakopter_move(), jakopter_reinit(), jakopter_stay(), jakopter_switch_camera(), and jakopter_takeoff().
char command[PACKET_SIZE] static
Definition at line 11 of file drone.c.
Referenced by send_cmd().
char command_args[ARGS_MAX][ARG_LEN] static
Definition at line 23 of file drone.c.
Referenced by send_cmd(), and set_cmd().
char command_logged[LOG_LEN] static
Definition at line 13 of file drone.c.
Referenced by jakopter_connect(), jakopter_log_command(), and send_cmd().
char* command_type = NULL static
Definition at line 22 of file drone.c.
Referenced by jakopter_connect(), send_cmd(), and set_cmd().
char * emergency_arg = "290717952" static
Definition at line 17 of file drone.c.
Referenced by jakopter_emergency().
char * land_arg = "290717696" static
Definition at line 16 of file drone.c.
Referenced by jakopter_land().
pthread_mutex_t mutex_cmd = PTHREAD_MUTEX_INITIALIZER static
Definition at line 33 of file drone.c.
Referenced by jakopter_connect(), jakopter_log_command(), send_cmd(), and set_cmd().
pthread_mutex_t mutex_stopped = PTHREAD_MUTEX_INITIALIZER static
Definition at line 35 of file drone.c.
Referenced by cmd_routine(), jakopter_connect(), and jakopter_disconnect().
volatile int stopped = 1
Definition at line 31 of file drone.c.
Referenced by cmd_routine(), jakopter_connect(), jakopter_disconnect(), and jakopter_log_command().
char* takeoff_arg = "290718208" static
Definition at line 15 of file drone.c.
Referenced by jakopter_takeoff().