Jakopter: src/lua_bindings.c File Reference
lua_bindings.c File Reference
#include <sched.h>
#include <lauxlib.h>
#include <lua.h>
#include "drone.h"
#include "navdata.h"
#include "com_channel.h"
#include "com_master.h"
#include "video.h"
#include "coords.h"
#include "network.h"
Functions
int jakopter_connect_lua (lua_State *L)
int jakopter_takeoff_lua (lua_State *L)
int jakopter_land_lua (lua_State *L)
int jakopter_rotate_left_lua (lua_State *L)
int jakopter_rotate_right_lua (lua_State *L)
int jakopter_slide_left_lua (lua_State *L)
int jakopter_slide_right_lua (lua_State *L)
int jakopter_forward_lua (lua_State *L)
int jakopter_backward_lua (lua_State *L)
int jakopter_up_lua (lua_State *L)
int jakopter_down_lua (lua_State *L)
int jakopter_disconnect_lua (lua_State *L)
int jakopter_reinit_lua (lua_State *L)
int jakopter_ftrim_lua (lua_State *L)
int jakopter_calib_lua (lua_State *L)
int jakopter_move_lua (lua_State *L)
int jakopter_stay_lua (lua_State *L)
int jakopter_emergency_lua (lua_State *L)
int jakopter_log_command_lua (lua_State *L)
int jakopter_is_flying_lua (lua_State *L)
int jakopter_height_lua (lua_State *L)
int jakopter_battery_lua (lua_State *L)
int jakopter_log_navdata_lua (lua_State *L)
int usleep_lua (lua_State *L)
int yield_lua (lua_State *L)
int jakopter_com_read_int_lua (lua_State *L)
int jakopter_com_read_float_lua (lua_State *L)
int jakopter_com_read_string_lua (lua_State *L)
int jakopter_com_write_int_lua (lua_State *L)
int jakopter_com_write_float_lua (lua_State *L)
int jakopter_com_write_string_lua (lua_State *L)
int jakopter_com_get_timestamp_lua (lua_State *L)
int jakopter_init_video_lua (lua_State *L)
int jakopter_stop_video_lua (lua_State *L)
int jakopter_switch_camera_lua (lua_State *L)
int jakopter_set_callback_lua (lua_State *L)
int jakopter_draw_icon_lua (lua_State *L)
int jakopter_draw_text_lua (lua_State *L)
int jakopter_draw_remove_lua (lua_State *L)
int jakopter_draw_resize_lua (lua_State *L)
int jakopter_draw_move_lua (lua_State *L)
int jakopter_init_coords_lua (lua_State *L)
int jakopter_stop_coords_lua (lua_State *L)
int jakopter_log_coords_lua (lua_State *L)
int jakopter_init_network_lua (lua_State *L)
int jakopter_stop_network_lua (lua_State *L)
int jakopter_cleanup_lua (lua_State *L)
static int create_cleanup_udata (lua_State *L)
JAKO_EXPORT int luaopen_libjakopter (lua_State *L)
Variables
static const luaL_Reg jakopterlib []
Function Documentation
static int create_cleanup_udata (lua_State * L) static
Create a metatable holding the cleanup function as the garbage collection event. Store a userdata with this metatable in the registry, so that it gets garbage collected when Lua exits, allowing the cleanup function to be executed.
Definition at line 506 of file lua_bindings.c.
References jakopter_cleanup_lua().
Referenced by luaopen_libjakopter().
int jakopter_backward_lua (lua_State * L)
Definition at line 95 of file lua_bindings.c.
References jakopter_backward(), and speed.
int jakopter_battery_lua (lua_State * L)
Definition at line 184 of file lua_bindings.c.
References jakopter_battery().
int jakopter_calib_lua (lua_State * L)
Definition at line 137 of file lua_bindings.c.
References jakopter_calib().
int jakopter_cleanup_lua (lua_State * L)
Cleanup function called when the library is unloaded. Makes sure all threads started by the library are terminated.
Definition at line 424 of file lua_bindings.c.
References jakopter_disconnect(), jakopter_is_flying(), jakopter_land(), jakopter_stop_coords(), jakopter_stop_network(), and jakopter_stop_video().
Referenced by create_cleanup_udata().
int jakopter_com_get_timestamp_lua (lua_State * L)
Definition at line 292 of file lua_bindings.c.
References jakopter_com_get_channel(), and jakopter_com_get_timestamp().
int jakopter_com_read_float_lua (lua_State * L)
Definition at line 220 of file lua_bindings.c.
References jakopter_com_get_channel(), and jakopter_com_read_float().
int jakopter_com_read_int_lua (lua_State * L)
Definition at line 208 of file lua_bindings.c.
References jakopter_com_get_channel(), and jakopter_com_read_int().
int jakopter_com_read_string_lua (lua_State * L)
Definition at line 232 of file lua_bindings.c.
References jakopter_com_get_channel(), jakopter_com_read_buf(), and jakopter_com_read_int().
int jakopter_com_write_float_lua (lua_State * L)
Definition at line 264 of file lua_bindings.c.
References jakopter_com_get_channel(), and jakopter_com_write_float().
int jakopter_com_write_int_lua (lua_State * L)
Definition at line 251 of file lua_bindings.c.
References jakopter_com_get_channel(), and jakopter_com_write_int().
int jakopter_com_write_string_lua (lua_State * L)
Definition at line 277 of file lua_bindings.c.
References jakopter_com_get_channel(), jakopter_com_write_buf(), and jakopter_com_write_int().
int jakopter_connect_lua (lua_State * L)
Definition at line 26 of file lua_bindings.c.
References jakopter_connect().
int jakopter_disconnect_lua (lua_State * L)
Definition at line 119 of file lua_bindings.c.
References jakopter_disconnect().
int jakopter_down_lua (lua_State * L)
Definition at line 111 of file lua_bindings.c.
References jakopter_down(), and speed.
int jakopter_draw_icon_lua (lua_State * L)
Drawing API
Definition at line 331 of file lua_bindings.c.
References jakopter_draw_icon().
int jakopter_draw_move_lua (lua_State * L)
Definition at line 375 of file lua_bindings.c.
References jakopter_draw_move().
int jakopter_draw_remove_lua (lua_State * L)
Definition at line 357 of file lua_bindings.c.
References jakopter_draw_remove().
int jakopter_draw_resize_lua (lua_State * L)
Definition at line 365 of file lua_bindings.c.
References jakopter_draw_resize().
int jakopter_draw_text_lua (lua_State * L)
Definition at line 345 of file lua_bindings.c.
References jakopter_draw_text().
int jakopter_emergency_lua (lua_State * L)
Definition at line 160 of file lua_bindings.c.
References jakopter_emergency().
int jakopter_forward_lua (lua_State * L)
Definition at line 87 of file lua_bindings.c.
References jakopter_forward(), and speed.
int jakopter_ftrim_lua (lua_State * L)
Definition at line 131 of file lua_bindings.c.
References jakopter_flat_trim().
int jakopter_height_lua (lua_State * L)
Definition at line 178 of file lua_bindings.c.
References jakopter_height().
int jakopter_init_coords_lua (lua_State * L)
Definition at line 387 of file lua_bindings.c.
References jakopter_init_coords().
int jakopter_init_network_lua (lua_State * L)
Definition at line 405 of file lua_bindings.c.
References jakopter_init_network().
int jakopter_init_video_lua (lua_State * L)
Definition at line 305 of file lua_bindings.c.
References jakopter_init_video().
int jakopter_is_flying_lua (lua_State * L)
Definition at line 172 of file lua_bindings.c.
References jakopter_is_flying().
int jakopter_land_lua (lua_State * L)
Definition at line 49 of file lua_bindings.c.
References jakopter_land().
int jakopter_log_command_lua (lua_State * L)
Definition at line 166 of file lua_bindings.c.
References jakopter_log_command().
int jakopter_log_coords_lua (lua_State * L)
Definition at line 397 of file lua_bindings.c.
References jakopter_log_coords().
int jakopter_log_navdata_lua (lua_State * L)
Definition at line 190 of file lua_bindings.c.
References jakopter_log_navdata().
int jakopter_move_lua (lua_State * L)
Definition at line 143 of file lua_bindings.c.
References jakopter_move().
int jakopter_reinit_lua (lua_State * L)
Definition at line 125 of file lua_bindings.c.
References jakopter_reinit().
int jakopter_rotate_left_lua (lua_State * L)
Definition at line 55 of file lua_bindings.c.
References jakopter_rotate_left().
int jakopter_rotate_right_lua (lua_State * L)
Definition at line 63 of file lua_bindings.c.
References jakopter_rotate_right().
int jakopter_set_callback_lua (lua_State * L)
Definition at line 323 of file lua_bindings.c.
References jakopter_set_callback().
int jakopter_slide_left_lua (lua_State * L)
Definition at line 71 of file lua_bindings.c.
References jakopter_slide_left(), and speed.
int jakopter_slide_right_lua (lua_State * L)
Definition at line 79 of file lua_bindings.c.
References jakopter_slide_right(), and speed.
int jakopter_stay_lua (lua_State * L)
Definition at line 154 of file lua_bindings.c.
References jakopter_stay().
int jakopter_stop_coords_lua (lua_State * L)
Definition at line 392 of file lua_bindings.c.
References jakopter_stop_coords().
int jakopter_stop_network_lua (lua_State * L)
Definition at line 413 of file lua_bindings.c.
References jakopter_stop_network().
int jakopter_stop_video_lua (lua_State * L)
Definition at line 311 of file lua_bindings.c.
References jakopter_stop_video().
int jakopter_switch_camera_lua (lua_State * L)
Definition at line 316 of file lua_bindings.c.
References jakopter_switch_camera().
int jakopter_takeoff_lua (lua_State * L)
Definition at line 43 of file lua_bindings.c.
References jakopter_takeoff().
int jakopter_up_lua (lua_State * L)
Definition at line 103 of file lua_bindings.c.
References jakopter_up(), and speed.
JAKO_EXPORT int luaopen_libjakopter (lua_State * L)
Definition at line 526 of file lua_bindings.c.
References create_cleanup_udata(), and jakopterlib.
int usleep_lua (lua_State * L)
Definition at line 196 of file lua_bindings.c.
int yield_lua (lua_State * L)
Definition at line 202 of file lua_bindings.c.
Variable Documentation
const luaL_Reg jakopterlib[] static
Definition at line 443 of file lua_bindings.c.
Referenced by luaopen_libjakopter().