Jakopter: include/navdata.h File Reference
navdata.h File Reference
#include "common.h"
#include "com_channel.h"
#include "com_master.h"
Data Structures
struct navdata_option
struct navdata
struct navdata_demo
union navdata_t
Macros
#define PORT_NAVDATA 5554
#define NAVDATA_INTERVAL 1/15
#define TAG_DEMO 0
#define TAG_CKS 0
#define NAVDATA_NREADS_INT 4
#define NAVDATA_NREADS_FLOAT 6
#define DEMO_LEN NAVDATA_NREADS_INT*(INT_LEN+1)+(NAVDATA_NREADS_FLOAT*FLOAT_LEN+1)+2
Enumerations
enum ctrl_states {
DEFAULT, INIT, LANDED, FLY,
HOVER, CTRL_USELESS_1, CTRL_USELESS_2, TAKEOFF,
MOVE, LAND, LOOP
}
enum fly_states {
FLY_OK, FLY_LOST_ALT, FLY_LOST_ALT_GO_DOWN, FLY_ALT_OUT_ZONE,
COMBINED_YAW, BRAKE, NO_VISION
}
enum hover_states {
HOVER_OK, HOVER_YAW, HOVER_YAW_LOST_ALT, HOVER_YAW_LOST_ALT_GO_DOWN,
HOVER_ALT_OUT_ZONE, HOVER_YAW_ALT_OUT_ZONE, HOVER_LOST_ALT, HOVER_LOST_ALT_GO_DOWN,
LOST_COM, LOST_COM_LOST_ALT, LOST_COM_LOST_ALT_TOO_LONG, LOST_COM_ALT_OK,
MAGNETO_CALIB, DEMO
}
enum takeoff_states { TAKEOFF_GROUND, TAKEOFF_AUTO }
enum move_states { GOTO_OK = 0, GOTO_LOST_ALT, GOTO_YAW }
enum land_states { CLOSED_LOOP, OPEN_LOOP, OPEN_LOOP_FAST }
enum loop_states { IMPULSION, OPEN_LOOP_CTRL, PLANIF_CTRL }
Functions
int navdata_connect (const char *drone_ip)
int navdata_disconnect ()
int jakopter_is_flying ()
int jakopter_battery ()
int jakopter_height ()
int navdata_no_sq ()
void debug_navdata_demo ()
const char * jakopter_navdata_timestamp ()
const char * jakopter_log_navdata ()
Macro Definition Documentation
#define DEMO_LEN NAVDATA_NREADS_INT*(INT_LEN+1)+(NAVDATA_NREADS_FLOAT*FLOAT_LEN+1)+2
Definition at line 17 of file navdata.h.
Referenced by jakopter_log_navdata().
#define NAVDATA_INTERVAL 1/15
Definition at line 10 of file navdata.h.
Referenced by navdata_routine().
#define NAVDATA_NREADS_FLOAT 6
Definition at line 15 of file navdata.h.
#define NAVDATA_NREADS_INT 4
Definition at line 14 of file navdata.h.
#define PORT_NAVDATA 5554
Definition at line 8 of file navdata.h.
Referenced by navdata_connect().
#define TAG_CKS 0
Definition at line 13 of file navdata.h.
#define TAG_DEMO 0
Definition at line 11 of file navdata.h.
Referenced by jakopter_battery(), jakopter_height(), and recv_cmd().
Enumeration Type Documentation
enum ctrl_states
Main value in the first 16 bits.
Enumerator
DEFAULT
INIT
LANDED
FLY
HOVER
CTRL_USELESS_1
CTRL_USELESS_2
TAKEOFF
MOVE
LAND
LOOP
Definition at line 22 of file navdata.h.
enum fly_states
Specific value in the last 16 bits.
Enumerator
FLY_OK
FLY_LOST_ALT
FLY_LOST_ALT_GO_DOWN
FLY_ALT_OUT_ZONE
COMBINED_YAW
BRAKE
NO_VISION
Definition at line 37 of file navdata.h.
enum hover_states
Enumerator
HOVER_OK
HOVER_YAW
HOVER_YAW_LOST_ALT
HOVER_YAW_LOST_ALT_GO_DOWN
HOVER_ALT_OUT_ZONE
HOVER_YAW_ALT_OUT_ZONE
HOVER_LOST_ALT
HOVER_LOST_ALT_GO_DOWN
LOST_COM
LOST_COM_LOST_ALT
LOST_COM_LOST_ALT_TOO_LONG
LOST_COM_ALT_OK
MAGNETO_CALIB
DEMO
Definition at line 47 of file navdata.h.
enum land_states
Enumerator
CLOSED_LOOP
OPEN_LOOP
OPEN_LOOP_FAST
Definition at line 75 of file navdata.h.
enum loop_states
Enumerator
IMPULSION
OPEN_LOOP_CTRL
PLANIF_CTRL
Definition at line 81 of file navdata.h.
enum move_states
Enumerator
GOTO_OK
GOTO_LOST_ALT
GOTO_YAW
Definition at line 69 of file navdata.h.
enum takeoff_states
Enumerator
TAKEOFF_GROUND
TAKEOFF_AUTO
Definition at line 64 of file navdata.h.
Function Documentation
void debug_navdata_demo ()
Print the content of received navdata.
Definition at line 288 of file navdata.c.
References navdata_demo::ardrone_state, navdata_demo::ctrl_state, data, navdata_t::demo, navdata_demo::header, mutex_navdata, navdata_demo::phi, navdata_demo::psi, navdata_demo::sequence, navdata_demo::size, navdata_demo::tag, and navdata_demo::theta.
int jakopter_battery ()
Returns
the battery charge in percentage or -1 if navdata are not received
Definition at line 247 of file navdata.c.
References data, navdata_t::demo, mutex_navdata, navdata::options, navdata_t::raw, navdata::sequence, navdata_option::tag, TAG_DEMO, and navdata_demo::vbat_flying_percentage.
Referenced by jakopter_battery_lua().
int jakopter_height ()
Returns
the height in millimeters or -1 if navdata are not received
Definition at line 263 of file navdata.c.
References navdata_demo::altitude, data, navdata_t::demo, mutex_navdata, navdata::options, navdata_t::raw, navdata::sequence, navdata_option::tag, and TAG_DEMO.
Referenced by jakopter_height_lua(), jakopter_land(), and jakopter_takeoff().
int jakopter_is_flying ()
Returns
a boolean
Definition at line 238 of file navdata.c.
References navdata::ardrone_state, data, mutex_navdata, and navdata_t::raw.
Referenced by jakopter_calib(), jakopter_cleanup_lua(), jakopter_flat_trim(), jakopter_is_flying_lua(), jakopter_land(), and jakopter_takeoff().
const char* jakopter_log_navdata ()
Return all the data stored with a timestamp.
Returns
a string containing the data under this format: "sec.nsec:data1 data2 " or NULL if stopped
Definition at line 303 of file navdata.c.
References navdata_demo::altitude, navdata_demo::ardrone_state, navdata_demo::ctrl_state, data, navdata_t::demo, DEMO_LEN, LOG_LEN, mutex_navdata, mutex_timestamp, navdata_demo::phi, navdata_demo::psi, stopped_navdata, navdata_demo::theta, timestamp, TSTAMP_LEN, navdata_demo::vbat_flying_percentage, navdata_demo::vx, navdata_demo::vy, and navdata_demo::vz.
Referenced by jakopter_log_navdata_lua().
const char* jakopter_navdata_timestamp ()
Return the timestamp of the last request: is_flying, etc. Must be called after the request, so be sure to store the result of the request before.
Returns
a string containing the timestamp under this format: "sec.nsec:" or NULL if stopped
int navdata_connect (const char * drone_ip)
Start navdata thread.
Parameters
drone_ip used by simulator, if you are with a real drone, set it to NULL
Returns
0 if success, -1 if error
Definition at line 167 of file navdata.c.
References addr_client_navdata, CHANNEL_NAVDATA, data, jakopter_com_add_channel(), mutex_stopped, navdata_init(), navdata_routine(), navdata_thread, PORT_NAVDATA, sock_navdata, stopped_navdata, and WIFI_ARDRONE_IP.
Referenced by jakopter_connect().
int navdata_disconnect ()
Stop navdata thread.
Returns
the pthread_join value or -1 if communication already stopped.
Definition at line 214 of file navdata.c.
References CHANNEL_NAVDATA, jakopter_com_remove_channel(), mutex_stopped, navdata_thread, sock_navdata, and stopped_navdata.
Referenced by jakopter_disconnect().
int navdata_no_sq ()
Returns
the sequence number of navdata
Definition at line 279 of file navdata.c.
References data, mutex_navdata, navdata_t::raw, and navdata::sequence.
Referenced by jakopter_land(), and jakopter_takeoff().