Jakopter: include/coords.h File Reference
coords.h File Reference
#include "com_channel.h"
#include "com_master.h"
#include "utils.h"
Macros
#define COORDS_NREADS 10
#define COORDS_TIMEOUT 2000
#define COORDS_INTERVAL 1
#define COORDS_BUF_SIZE (FLOAT_LEN + 1)*COORDS_NREADS + 1
#define COORDS_FILENAME "/tmp/jakopter_coords.txt"
Functions
int jakopter_init_coords ()
int jakopter_stop_coords ()
const char * jakopter_log_coords ()
Macro Definition Documentation
#define COORDS_BUF_SIZE (FLOAT_LEN + 1)*COORDS_NREADS + 1
Definition at line 14 of file coords.h.
Referenced by jakopter_log_coords(), and read_coords().
#define COORDS_FILENAME "/tmp/jakopter_coords.txt"
Definition at line 15 of file coords.h.
Referenced by jakopter_init_coords(), and jakopter_stop_coords().
#define COORDS_INTERVAL 1
Definition at line 12 of file coords.h.
Referenced by coords_routine().
#define COORDS_NREADS 10
Definition at line 10 of file coords.h.
Referenced by coords_routine(), and jakopter_init_coords().
#define COORDS_TIMEOUT 2000
Definition at line 11 of file coords.h.
Referenced by jakopter_init_coords().
Function Documentation
int jakopter_init_coords ()
Definition at line 98 of file coords.c.
References addr_server_coords, CHANNEL_COORDS, COORDS_FILENAME, COORDS_NREADS, coords_routine(), coords_thread, COORDS_TIMEOUT, jakopter_com_add_channel(), jakopter_com_write_float(), mutex_stopped_coords, recv_ready, sock_coords, and stopped_coords.
Referenced by jakopter_init_coords_lua().
const char* jakopter_log_coords ()
Definition at line 171 of file coords.c.
References COORDS_BUF_SIZE, log_coords, mutex_log, stopped_coords, and TSTAMP_LEN.
Referenced by jakopter_log_coords_lua().
int jakopter_stop_coords ()
Definition at line 147 of file coords.c.
References CHANNEL_COORDS, COORDS_FILENAME, coords_thread, jakopter_com_remove_channel(), mutex_stopped_coords, sock_coords, and stopped_coords.
Referenced by jakopter_cleanup_lua(), and jakopter_stop_coords_lua().